### PR TITLE
Update Azure.DCAP.Windows v0.0.3 to Microsoft.Azure.DCAP v1.3.0

### LINKED ISSUE #2627: Upgrade DCAP client to 1.2
OE is currently using a 0.03 version of the DCAP client, with 1.2 out we should upgrade the CI and scripts to use the latest version.

### PR DESCRIPTION
**Pull request by CodeMonkeyLeet**
Fixes #2627

Signed-off-by: Simon Leet <simon.leet@microsoft.com>

### CODE REVIEW

**Comment by CodeMonkeyLeet** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
@CodeMonkeyLeet @yufjiang merging now, after merge we need to kick off a rebuild. Will take some time., thanks for your patience!

**Pull request merged**
