### PR TITLE
Allow libc tests to be run individually

### LINKED ISSUE #2487: Run libc tests separately
Currently each libc test is run as a single test. This makes it very challenging to troubleshoot which specific test is failing. Additionally, if one test fails, the others are not even attempted.

Match the libcxx tests in putting each test in a separate enclave binary and running them as separate tests.

### PR DESCRIPTION
**Pull request by jhand2**
The libc tests currently run all as a single test and if one fails then the tests stop running. Add the cmake option OE_SEPARATE_LIBC_TESTS which will lead ctest to run each libc test as a separate case.

Additionally, add a command-line option to the libc test host to allow a single test to be run at a time to support the cmake flag.

Fixes #2487

This is v2 of an earlier PR #2490

### CODE REVIEW

**Comment by jhand2** [comment]
bors try

**Comment by jhand2** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by jhand2** [comment]
try again to resolve platform error

bors try

**Comment by jhand2** [comment]
Potential infra issues

bors try

**Comment by jhand2** [comment]
trying on new infra

bors try

**Comment by jhand2** [comment]
bors try

**Comment by jhand2** [comment]
> LGTM
> 
> Before merging this in master, run the full C/C++ testsuite (we only run a small subset by default) and make sure that there is no build/test time regression.

I turned on ENABLE_FILL_LIBCXX_TESTS and confirmed no regressions.

bors r+

**Pull request merged**
