### PR TITLE
Updated oesgx README.md to reflect current output

### LINKED ISSUE #1666: oesgx tool needs update to its README.md file
The oesgx tool was changed to now output more information than just the SGX version it supports (like EPC size). The documentation here should explain everything it can potentially output: https://github.com/Microsoft/openenclave/tree/master/tools/oesgx

### PR DESCRIPTION
**Pull request by anitagov**
Resolves #1666 . Updated oesgx README.md to print all the details of the output which includes level of support of SGX (FLC or not), SGX1/SGX2, Max Enclave Size and EPC size.

### CODE REVIEW

**Comment by yakman2020** [comment]
@johnkord Could you review and approve?

**Comment by johnkord** [comment]
Wow that was funny, three of us reviewed this within a minute of each other :)

**Comment by yakman2020** [comment]
Fixed by PR 2002

**Comment by yakman2020** [comment]
Fixes issue #2002

**Comment by yakman2020** [comment]
Fixes issue #1666

**Comment by anitagov** [comment]
Thanks guys.

**Pull request merged**
