### PR TITLE
Infrastructure - validate Docker installation and remove clang-10 images

### PR DESCRIPTION
**Pull request by CyanDevs**
* Validate Docker is installed by the installer. In 2 occasions Ansible reported Docker installation task was completed - but Docker was not actually installed.
* Remove clang-10 images from image build pipeline as we no longer test with clang-10

### CODE REVIEW

**Review by mingweishih — APPROVED** [review]

**Review by radhikaj — APPROVED** [review]

**Comment by CyanDevs** [comment]
Override Bors due to repeated errors.

**Pull request merged**
