### PR TITLE
OpenSSF Badge Score

### PR DESCRIPTION
**Pull request by Salkimmich**
OpenSSF Badge Score Added. This % score is currently "owned" by @dthaler, and will need to be updated with the following for a more complete score. Tag me to any issues or PRs if I can help with any of the following:

1. Security: [Review Cryptographic Best Practices and choose N/A if not applicable](https://www.bestpractices.dev/en/projects/6187#security)
2. Analysis: Confirm use of Static and Dynamic Analysis Tooling, or reasoning for non-usage
3. The scan currently shows No Vulnerability reporting, but [Vuln Reporting](https://www.bestpractices.dev/en/projects/6187#security) is clearly available

### CODE REVIEW

**Comment by dcmiddle** [comment]
@radhikaj I don't remember if we discussed this in the last update to the CCC TAC. If not feel free to reach out to @Salkimmich for context...

This is the PR to add the best practices badge status to your repo.
You and your fellow maintainers should walk through each best practice (follow the badge link) and decide whether or not that best practice is being followed. Then perhaps create issues to address any gaps.
If you don't have access to change the status of an item on the badge site @Salkimmich can facilitate.

Thanks!

**Comment by dcmiddle** [comment]
@Salkimmich  you are missing your sign-off on the commit (see the DCO check failure).

**Comment by dthaler** [comment]
@radhikaj I'm happy to transfer ownership, should I get it changed to you?

The process is that I have to open an issue in the badge repo like I did for this one: https://github.com/coreinfrastructure/best-practices-badge/issues/2086

**Comment by radhikaj** [comment]
> @radhikaj I'm happy to transfer ownership, should I get it changed to you?
> 
> The process is that I have to open an issue in the badge repo like I did for this one: [coreinfrastructure/best-practices-badge#2086](https://github.com/coreinfrastructure/best-practices-badge/issues/2086)

Sure. Please transfer to me. Thanks @dthaler

**Comment by radhikaj** [comment]
> @radhikaj I don't remember if we discussed this in the last update to the CCC TAC. If not feel free to reach out to @Salkimmich for context...
> 
> This is the PR to add the best practices badge status to your repo. You and your fellow maintainers should walk through each best practice (follow the badge link) and decide whether or not that best practice is being followed. Then perhaps create issues to address any gaps. If you don't have access to change the status of an item on the badge site @Salkimmich can facilitate.
> 
> Thanks!

Thanks @dcmiddle

**Comment by dthaler** [comment]
> Sure. Please transfer to me. Thanks @dthaler

Ok, filed https://github.com/coreinfrastructure/best-practices-badge/issues/2151

**Review by radhikaj — APPROVED** [review]

**Review by dcmiddle — APPROVED** [review]

**Review by dthaler — APPROVED** [review]

**Comment by Salkimmich** [comment]
@dthaler I believe this is ready to merge, let me know if it's still blocked.

**Comment by dcmiddle** [comment]
@radhikaj , Sal added their signed-off-by. This should be good to go now. You might need to authorize jenkins if you need that to run before merging, but this is a one line readme addition.

**Comment by CyanDevs** [comment]
@dcmiddle @Salkimmich thanks for this. Now that @radhikaj is the owner, could we update the score for requirements that are undetermined? E.g.
image

**Comment by dcmiddle** [comment]
@CyanDevs yes that should be entirely within Radhika's control.  :)
A good practice is that for anything non-obvious maintainers should discuss at a community meeting. 
The point of the badge is less about checking the boxes and more about all the maintainers having the same understanding and expectations for the maintenance of the project.

**Pull request merged**
