### PR TITLE
Add Andy Chen to committer

### PR DESCRIPTION
**Pull request by yentsanglee**
Add Andy Chen to committer and sig attestation approver

### CODE REVIEW

**Review by radhikaj — APPROVED** [review]

**Review by CyanDevs — APPROVED** [review]

**Review by qiucwang — APPROVED** [review]

**Review by anche-is-andy — APPROVED** [review]

**Comment by dthaler** [comment]
@radhikaj my understanding of https://github.com/openenclave/openenclave/blob/master/docs/Community/governance/charter.md is that the CGC approves committers, but I don't see the CGC added as reviewers of this PR.  Let me know if your understanding is different from mine.

**Comment by dthaler** [comment]
Now that PR #4425 is merged, this one is good to go.

**Review by dthaler — APPROVED** [review]

**Comment by radhikaj** [comment]
Thanks for the approvals. The commit was cherry-picked into https://github.com/openenclave/openenclave/pull/4429 and that was merged. I am closing this PR.

**Pull request closed without merging**
