### PR TITLE
Removed code related to deprecation of strftime

### PR DESCRIPTION
**Pull request by vtikoo**
### Summary
- Removed time.h related deprecations from 3rdparty/musl/deprecations.h
- Removed libc/time.c, which included stubs for strftime and strftime_l
- Added 3rdparty/musl/src/time/strftime.c to oelibc sources

 
Signed-off-by: Vikas Tikoo <vitikoo@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by radhikaj** [comment]
@vtikoo What is the rationale for removing it from the depreciated APIs list?

**Comment by vtikoo** [comment]
@radhikaj strftime is a supported function from within enclaves built with the intel sgx sdk. And based on discussion with @mikbras, there weren't any strong reasons for deprecating it openenclave support libc.

**Comment by radhikaj** [comment]
Thanks for the explanation!

**Comment by radhikaj** [comment]
Bors r+

**Pull request merged**
