### PR TITLE
Sign oecert enclave and verify signer id

### PR DESCRIPTION
**Pull request by qiucwang**
Generate random key pair at `oecert` build time. Sign the `oecert_enc` with the private key and verify the `signer_id` with the public key.
Signed-off-by: Qiucheng Wang <qiucwang@microsoft.com>

### CODE REVIEW

**Review by yentsanglee — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]

**Comment by qiucwang** [comment]
Bros failed at:
```
[6674/7235] cd /home/oeadmin/workspace/pipelines/Azure-Linux/tests/tools/oecert/enc && /home/oeadmin/workspace/pipelines/Azure-Linux/build/output/bin/oesign sign -e /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/oecert_enc-lvi-cfg -c enc.conf -k /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc/oecert_enc_private.pem
FAILED: tests/tools/oecert/enc/oecert_enc-lvi-cfg.signed 
```
The `oecert_enc_private.pem` was deleted after `oecert/oecert_enc` was signed so it's not found when pipeline tried to sign `oecert_enc-lvi-cfg`.
```
[6405/7235] cd /home/oeadmin/workspace/pipelines/Azure-Linux/tests/tools/oecert/enc && /home/oeadmin/workspace/pipelines/Azure-Linux/build/output/bin/oesign sign -e /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/oecert_enc -c enc.conf -k /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc/oecert_enc_private.pem
Created /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/oecert_enc.signed
[6406/7235] cd /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc && rm -f /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc/oecert_enc_private.pem
```
Why key generation was not performed when `oecert_enc-lvi-cfg` was built?

**Comment by qiucwang** [comment]
bors try

**Comment by qiucwang** [comment]
bors try

**Comment by qiucwang** [comment]
bors try

**Comment by qiucwang** [comment]
bors retry

**Comment by qiucwang** [comment]
bors try

**Comment by qiucwang** [comment]
bors try

**Comment by qiucwang** [comment]
bors try

**Comment by qiucwang** [comment]
bors try

**Review by ryanhsu19 — APPROVED** [review]

**Comment by mingweishih** [comment]
> Bros failed at:
> 
> ```
> [6674/7235] cd /home/oeadmin/workspace/pipelines/Azure-Linux/tests/tools/oecert/enc && /home/oeadmin/workspace/pipelines/Azure-Linux/build/output/bin/oesign sign -e /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/oecert_enc-lvi-cfg -c enc.conf -k /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc/oecert_enc_private.pem
> FAILED: tests/tools/oecert/enc/oecert_enc-lvi-cfg.signed
> cd /home/oeadmin/workspace/pipelines/Azure-Linux/tests/tools/oecert/enc && /home/oeadmin/workspace/pipelines/Azure-Linux/build/output/bin/oesign sign -e /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/oecert_enc-lvi-cfg -c enc.conf -k /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc/oecert_enc_private.pem
> /home/oeadmin/workspace/pipelines/Azure-Linux/build/output/bin/oesign ERROR: Failed to load file: /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc/oecert_enc_private.pem
> ```
> 
> The `oecert_enc_private.pem` was deleted after `oecert/oecert_enc` was signed so it's not found when pipeline tried to sign `oecert_enc-lvi-cfg`.
> 
> ```
> [6405/7235] cd /home/oeadmin/workspace/pipelines/Azure-Linux/tests/tools/oecert/enc && /home/oeadmin/workspace/pipelines/Azure-Linux/build/output/bin/oesign sign -e /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/oecert_enc -c enc.conf -k /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc/oecert_enc_private.pem
> Created /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/oecert_enc.signed
> [6406/7235] cd /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc && rm -f /home/oeadmin/workspace/pipelines/Azure-Linux/build/tests/tools/oecert/enc/oecert_enc_private.pem
> ```
> 
> Looks like key generation was not performed when `oecert_enc-lvi-cfg` was built. @mingweishih @BRMcLaren do you have any idea? And the naming of `oecert_enc-lvi-cfg` might affect `oecert` functioning as enclave name was [hardcoded here](https://github.com/openenclave/openenclave/pull/3919).

Did you resolve the issue? Also, please squash the comments. Thanks!

**Comment by qiucwang** [comment]
> Did you resolve the issue? Also, please squash the comments. Thanks!
Yes. I kept the private key for now as attestation sample did and we will eventually replace it with an official OESDK signing key later.

**Pull request merged**
