### PR TITLE
Use sizeof on the whole structure instead of the pointer

### LINKED ISSUE #2009: Calling sizeof on a pointer
We found a couple of instances where a pointer is passed into `sizeof` operator. This is a known vulnerability:  https://cwe.mitre.org/data/definitions/467.html

### PR DESCRIPTION
**Pull request by jxyang**
Fixes #2009

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Comment by yakman2020** [comment]
@jxyang Was there an issue associated with this PR?

**Comment by jxyang** [comment]
@yakman2020 #2009 is the issue.

**Pull request merged**
