### PR TITLE
Move Andy to emeritus approver status

### PR DESCRIPTION
**Pull request by andschwa**
So I stop getting requested by Dependabot etc.

### CODE REVIEW

**Review by mingweishih — APPROVED** [review]

**Review by rs-- — APPROVED** [review]

**Comment by rs--** [comment]
@andschwa Could you please sign your commit? Thanks!

**Comment by andschwa** [comment]
I made it on GitHub, it's already signed. I don't have another way to sign at the moment. Feel free to amend with your own signature if you need.
Screen Shot 2021-06-01 at 3 40 20 PM

**Pull request merged**
