### PR TITLE
Fix libcxxrt test result on Windows.

### PR DESCRIPTION
**Pull request by nonpolarity**
The test result is OS-specific that log file has different line endings on Windows and other OS. Git always adjusts the line endings automatically. Thus this test has a prerequisite that git must execute on the same platform as on which platform the test runs. For example, git on cygwin changes line endings to lf and test on Windows expects crlf, then test will fail.
This change make the libcxxrt test stateless.

Signed-off-by: Alvin Chen <alvin@chen.asia>

### CODE REVIEW

**Comment by nonpolarity** [comment]
bors try

**Comment by nonpolarity** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

Ignore me, I'm testing a back-end CI item.

**Pull request merged**
