### PR TITLE
Don't crash if oe_get_report is used in simulation mode

### PR DESCRIPTION
**Pull request by thomasten**
Instead return OE_UNSUPPORTED.

### CODE REVIEW

**Review by dthaler — APPROVED** [review]
Looks good to me, thanks!

**Review by anakrish — APPROVED** [review]
LGTM. Thanks!

**Comment by anakrish** [comment]
bors try

**Comment by thomasten** [comment]
amended fix for failing test

**Comment by anakrish** [comment]
bors try

**Pull request merged**
