### PR TITLE
Adding an option to disable building oegenerate tool

### PR DESCRIPTION
**Pull request by mrragava**
oegenerate executable tool cannot link fuzzing enabled libraries, When building OE with ENABLE_FUZZING turned ON, OE libraries will be linked with fuzzing libraries. Executables has to be built as libfuzzer target to link OE fuzzing libraries.

Since oegenerate tool is not required for fuzzing, Added a flag to disable building oegenerate.

Signed-off-by: Ragavan Dasarathan <mrragava@gmail.com>

### CODE REVIEW

**Review by mingweishih — APPROVED** [review]

**Comment by anakrish** [comment]
@mrragava Doesn't the same problem apply to other executables like oesign?

**Comment by mrragava** [comment]
> @mrragava Doesn't the same problem apply to other executables like oesign?

This incompatibility occurs only when the tools link liboehost. oesign doesn't seems to link liboehost.

**Review by ryanhsu19 — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]

**Review by anakrish — APPROVED** [review]

**Review by ryanhsu19 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
