### PR TITLE
Update ansible script to use Azrure dcap client version 1.5 for RHEL.

### PR DESCRIPTION
**Pull request by nonpolarity**
Update ansible script to use Azrure dcap client version 1.5 for RHEL, since the latest version 1.5 is released:

- Added caching of all collateral
- Added ability to enable debug logging independently of logging callback

Signed-off-by: Alvin Chen <alvin@chen.asia>

### CODE REVIEW

**Comment by nonpolarity** [comment]
bors try

**Comment by anakrish** [comment]
This PR seems to contradict the following comment:
https://github.com/openenclave/openenclave/pull/3067#issuecomment-632919701
> we don't specify a version for the package in ansible. The same is true for the libsgx packages. So whenever the apt repo gets updated, we automatically start using it.

Do ansible scripts require versions or do we always pick the latest versions?

**Comment by jhand2** [comment]
> This PR seems to contradict the following comment:
> [#3067 (comment)](https://github.com/openenclave/openenclave/pull/3067#issuecomment-632919701)
> 
> > we don't specify a version for the package in ansible. The same is true for the libsgx packages. So whenever the apt repo gets updated, we automatically start using it.
> 
> Do ansible scripts require versions or do we always pick the latest versions?

>This PR seems to contradict the following comment:
> https://github.com/openenclave/openenclave/pull/3067#issuecomment-632919701
> > we don't specify a version for the package in ansible. The same is true for the libsgx packages. So whenever the apt repo gets updated, we automatically start using it.

> Do ansible scripts require versions or do we always pick the latest versions?

What I said only applies to the ubuntu packages. The azure dcap client doesn't publish an RPM packages, so we have to go through some extra steps to pull the source and build it from the github releases. In that case you do have to specify which version you want to pull.

**Comment by nonpolarity** [comment]
> 
> 
> > This PR seems to contradict the following comment:
> > [#3067 (comment)](https://github.com/openenclave/openenclave/pull/3067#issuecomment-632919701)
> > > we don't specify a version for the package in ansible. The same is true for the libsgx packages. So whenever the apt repo gets updated, we automatically start using it.
> > 
> > 
> > Do ansible scripts require versions or do we always pick the latest versions?
> 
> What I said only applies to the ubuntu packages. The azure dcap client doesn't publish an RPM package, so we have to go through some extra steps to pull the source and build it from the github releases. In that case you do have to specify which version you want to pull.

Yes on RHEL the situation is as @jhand2 described. The good thing is Azure dcap client owner are trying to release a rpm for RHEL. This pr is also used to verify the new version is good on RHEL.

**Pull request merged**
