### PR TITLE
remove unused variable from server/client files

### PR DESCRIPTION
**Pull request by manojrupireddy**
remove unused variable from server/client files
Signed-off-by: manoj rupireddy <marupire@microsoft.com>

### CODE REVIEW

**Review by mingweishih — APPROVED** [review]

**Comment by radhikaj** [comment]
Looks good! Can you also follow up to see why this did not repo in CI

**Review by radhikaj — APPROVED** [review]

**Review by anakrish — APPROVED** [review]
LGTM

**Review by dthaler — APPROVED** [review]

**Comment by radhikaj** [comment]
Bors r+

**Comment by radhikaj** [comment]
Bors r+

**Comment by radhikaj** [comment]
bors delegate+

**Comment by radhikaj** [comment]
Bors r+

**Pull request merged**
