### PR TITLE
Update version to v0.14

### PR DESCRIPTION
**Pull request by radhikaj**
Signed-off-by: Radhika Jandhyala <radhikaj@microsoft.com>

### CODE REVIEW

**Review by rs-- — APPROVED** [review]

**Review by nonpolarity — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]

**Comment by dthaler** [comment]
What about updating the VS extension to 0.14 too?
Looks like it's still on 0.12, so are we missing a step in the overall release process?

**Comment by rs--** [comment]
> What about updating the VS extension to 0.14 too?
> Looks like it's still on 0.12, so are we missing a step in the overall release process?

I ran into some issues on the v0.13 release, and got side tracked. I'll be sure that the v0.14 VS extension is published for this release.

**Pull request merged**
