### PR TITLE
Handle new error code from DCAP 1.16

### PR DESCRIPTION
**Pull request by asvrada**
DCAP new version (1.15 -> 1.16) introduces a new error code:
https://github.com/intel/SGXDataCenterAttestationPrimitives/blame/925499dffaf8fbef52c0bbc57204632d15cc84bf/QuoteGeneration/quote_wrapper/common/inc/sgx_ql_lib_common.h#L142

This PR is similar to #4689

### CODE REVIEW

**Comment by asvrada** [comment]
bors try

**Comment by asvrada** [comment]
I think there should be a one-to-one mapping from `quote3_error_t` to `oe_result_t`, currently `get_oe_result_t` does this mapping but doesn't cover every error code.

**Review by mingweishih — APPROVED** [review]

**Review by radhikaj — APPROVED** [review]
bors r+

**Comment by asvrada** [comment]
bors try

**Pull request merged**
