### PR TITLE
Update changelog and version for v0.16.0

### PR DESCRIPTION
**Pull request by rs--**

### CODE REVIEW

**Review by CyanDevs — APPROVED** [review]

**Comment by yentsanglee** [comment]
> - Publish test tool `oecert`.

oegenerate

---
Refers to: CHANGELOG.md:21 in c2e8aa1. [](commit_id = c2e8aa1fcf9b550a293487892b950204519e176d, deletion_comment = False)

**Comment by yentsanglee** [comment]
>   - The tool, currently under the `tools` directory, was originally under the `tests/tools` directory.

named 'oecert'

---
Refers to: CHANGELOG.md:22 in c2e8aa1. [](commit_id = c2e8aa1fcf9b550a293487892b950204519e176d, deletion_comment = False)

**Comment by yentsanglee** [comment]
>   - OE_CLAIM_TCB_DATE

Please remove these 2 items

---
Refers to: CHANGELOG.md:31 in c2e8aa1. [](commit_id = c2e8aa1fcf9b550a293487892b950204519e176d, deletion_comment = False)

**Review by yentsanglee — APPROVED** [review]

**Pull request merged**
