### PR TITLE
Remove unused stubs

### PR DESCRIPTION
**Pull request by anakrish**
New syscall dispatching no longer requires these stubs to be present.
The linker is already eliminating these stubs in the enclave binary.
Remove these stubs in code.

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Review by mingweishih — COMMENTED** [review]
Thanks for the cleaning up! Can you also comment on why we can't eliminate the remaining stubs?

**Comment by anakrish** [comment]
> Thanks for the cleaning up! Can you also comment on why we can't eliminate the remaining stubs?

The remaining stubs lead to link errors implying that they are needed for now. My hunch is that we'd need to tweak the system edls or do additional imports in test edls for these system calls. My plan is to investigate these remaining stubs in background over the next few weeks.

**Review by mingweishih — APPROVED** [review]
LGTM!

**Comment by anakrish** [comment]
bors try

**Review by manojrupireddy — APPROVED** [review]

**Comment by anakrish** [comment]
@radhikaj I need to make some tweaks to fix the failures.

**Comment by anakrish** [comment]
Closing this. Will resubmit at appropriate time.

**Comment by anakrish** [comment]
bors try

**Pull request closed without merging**
