### PR TITLE
[Docker] Add Step to enable exec permissions for scripts in dockerfile

### PR DESCRIPTION
**Pull request by arlynch**
### Description

Introduces a step in the linux docker images to enable execute permissions for ansible related shell scripts. This is added in case permissions are removed for any reason, and ensures the docker image can be built successfully.

### Verification
Verified through jenkins pipelines that Docker image is successfully built.

### CODE REVIEW

**Comment by asvrada** [comment]
Is this possible to `+x` to the file in the repo? Would docker preserve permission when copying file?

**Review by asvrada — APPROVED** [review]

**Comment by arlynch** [comment]
The permissions currently exist on the file in the repo, however, I have encountered situations where that can get cleared (namely in private pipelines not running on jenkins). This step is to ensure that even if they are cleared it is not an issue for docker.

**Review by CyanDevs — CHANGES_REQUESTED** [review]
Although it is not Don't run this as a separate step, but merge this into the RUN step below. This makes for a more efficient build as it reduces the number of layers which decreases the build time and image size.

**Review by CyanDevs — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
