### PR TITLE
Nsis

### PR DESCRIPTION
**Pull request by BRMcLaren**
We encountered an issue within the CI/CD infrastructure while testing packages. The `makensis` binary tool is needed by `cpack.exe` to rectify this issue and prevent a repetition of this.

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-E2E-Testing/detail/OpenEnclave-E2E-Testing/84/pipeline

E2E check

**Comment by BRMcLaren** [comment]
@ionutbalutoiu @oprinmarius @Francis-Liu 

Could you take a look? This is blocking @Francis-Liu

**Comment by jhand2** [comment]
@BRMcLaren Could you update the PR description with what exactly the NSIS compiler is needed for? From an initial search of what this even is, it's unclear to me what we need it for.

**Comment by Francis-Liu** [comment]
> 
> 
> @BRMcLaren Could you update the PR description with what exactly the NSIS compiler is needed for? From an initial search of what this even is, it's unclear to me why we need it.

@jhand2 Thanks for the comments. `makensis` binary tool is needed by `cpack.exe`, which is needed by this pending [PR](https://github.com/openenclave/openenclave/pull/2531). Specifically, the missing of NSIS compiler causes this [error](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/34/pipeline).

**Comment by oeciteam** [comment]
Bors try

**Pull request merged**
