### PR TITLE
Added Windows simulation package tests

### PR DESCRIPTION
**Pull request by rs--**

### CODE REVIEW

**Review by CyanDevs — APPROVED** [review]

**Review by radhikaj — APPROVED** [review]

**Comment by radhikaj** [comment]
71 packages can be upgraded. Run 'apt list --upgradable' to see them.

W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/download_01_org_intel_sgx_sgx_repo_ubuntu.list:1 and /etc/apt/sources.list.d/intel-sgx.list:1

W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/msprod.list:1 and /etc/apt/sources.list.d/packages_microsoft_com_ubuntu_18_04_prod.list:1

Checking for locks...



WARNING: apt does not have a stable CLI interface. Use with caution in scripts.



E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)

E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

script returned exit code 100

**Review by anakrish — APPROVED** [review]

**Pull request merged**
