### PR TITLE
Correctly determine compiler.

### PR DESCRIPTION
**Pull request by anakrish**
Use find_program instead of the undocumented CMAKE_C_COMPILER_NAMES.
Also pass the compiler onto oeedger8r-cpp external project.

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Review by mingweishih — APPROVED** [review]
LGTM

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try-

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try-

**Comment by anakrish** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Review by CodeMonkeyLeet — APPROVED** [review]
LGTM

**Pull request merged**
