### PR TITLE
<WIP> add overwrite action to host verification installation fixes #3351

### LINKED ISSUE #3351: CI Host Verification Installation Failure
It seems that the host verification package is being installed twice in the same workspace and is failing due to not overwriting the current installation. This should be installed in different workspaces, which is already implemented.

Causing CI [failures ](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/1152/pipeline/) and needs investigation.
```
CPack: Create package
Attempting to build package from 'CPack.NuGet.nuspec'.
Successfully created package 'C:\Users\oeadmin\workspace\pipelines\Azure-Linux\build\_CPack_Packages\win64\NuGet\open-enclave-0.10.0-win64\open-enclave.OEHOSTVERIFY.0.10.0.nupkg'.
Attempting to build package from 'CPack.NuGet.nuspec'.
Successfully created package 'C:\Users\oeadmin\workspace\pipelines\Azure-Linux\build\_CPack_Packages\win64\NuGet\open-enclave-0.10.0-win64\open-enclave.0.10.0.nupkg'.
CPack: - package: C:/Users/oeadmin/workspace/pipelines/Azure-Linux/build/open-enclave.0.10.0.nupkg generated.
CPack: - package: C:/Users/oeadmin/workspace/pipelines/Azure-Linux/build/open-enclave.OEHOSTVERIFY.0.10.0.nupkg generated.
tests\host_verify\host\sgx_cert_ec.der
tests\host_verify\host\sgx_cert_ec_bad.der
tests\host_verify\host\sgx_cert_rsa.der
tests\host_verify\host\sgx_cert_rsa_bad.der
        4 file(s) copied.
tests\host_verify\host\sgx_report.bin
tests\host_verify\host\sgx_report_bad.bin
        2 file(s) copied.

Feeds used:
  C:\Users\oeadmin\workspace\pipelines\Azure-Linux\build
Package "open-enclave.OEHOSTVERIFY.0.10.0" is already installed.
Overwrite C:\openenclave\bin\host_verify.exe (Yes/No/All)? 
Overwrite C:\openenclave\bin\host_verify.exe (Yes/No/All)? 
```

### PR DESCRIPTION
**Pull request by BRMcLaren**
Signed-off-by: Brett McLaren <brmclare@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
FileConflictAction is not being recognized.
Is it possible you delete the directory and then install?

**Comment by BRMcLaren** [comment]
Let me try with the directory removal, if we install to oe_hostverify, I suspect the same issue will persist.

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try-

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Pull request closed without merging**
