### PR TITLE
Update VS Extension

### PR DESCRIPTION
**Pull request by rs--**
Updated project files for VS Extension release version 0.14.34
- Upgrade from Clang-7 to Clang-8
- Updated library reference to `oecryptombedtls`
- Updated packages

### CODE REVIEW

**Comment by rs--** [comment]
I'll start the extension release process for v0.14.34 once this is merged. @dthaler @radhikaj

**Review by dthaler — APPROVED** [review]
Looks good to me

**Review by mingweishih — APPROVED** [review]
Thanks for doing this!

**Comment by mingweishih** [comment]
bors delegate=rs--

**Pull request merged**
