### PR TITLE
[SGX-LKL only] Add X flag to memory pages to successfully verify SGX-LKL attestation evidence.

### PR DESCRIPTION
**Pull request by wintersteiger**
Just adds the X flag in two more places. 

Signed-off-by: Christoph M. Wintersteiger <cwinter@microsoft.com>

### CODE REVIEW

**Comment by wintersteiger** [comment]
@jhand2 while you're at it, could you also rebase `feature/sgx-lkl-support` onto master again? Thanks!

**Comment by jhand2** [comment]
@wintersteiger I rebased master into this branch. move your commit to a branch based on that? Git gets confused on rebases and thinks all the commits are different.

**Comment by wintersteiger** [comment]
@jhand2 Sure, no problem, I wasn't able to predict which way around you'd get to those things :)

**Comment by wintersteiger** [comment]
Done!

**Comment by jhand2** [comment]
Ok, looks good. Thanks!

**Pull request merged**
