### PR TITLE
Update to use azure dcap client 1.6.0

### PR DESCRIPTION
**Pull request by deschuma**
Azure DCAP Client 1.5.0 introduced a bug which resulted in an exception being thrown if the logging callback and the AZDCAP_DEBUG_LOG_LEVEL environment variable were both undefined.

This has been tested on Ubuntu 16, 18 and Windows server 2016.

### CODE REVIEW

**Comment by anakrish** [comment]
@BRMcLaren @CodeMonkeyLeet How do we make sure that DCAP does not cause any regressions?
The last PR for updating DCAP was submitted just 15 days ago: https://github.com/openenclave/openenclave/pull/3067
As described in this PR, the last update introduced bugs; but was not caught anywhere in the testing pipeline.

**Comment by deschuma** [comment]
@anakrish IMO opinion this a was a miss on my part. The test should have been added as part of the Azure DCAP unit testing in the last PR. 

I suspect most users and all the tests are enabling OE SDK logging. MAA does not do this which is how we found the bug.
I'd suggest OE SDK consider adding a test configuration for no logging

**Comment by BRMcLaren** [comment]
@deschuma would you mind rebasing your branch?

I pushed some CI fixes this morning and need them in your branch to validate the rebuild.

**Comment by BRMcLaren** [comment]
@anakrish 
> As described in this PR, the last update introduced bugs; but was not caught anywhere in the testing pipeline.

That's actually not true. We had [regressions] (https://oe-jenkins-tf.westeurope.cloudapp.azure.com/job/CI-CD_Infrastructure/job/OpenEnclave-Rebuild-Infrastructure/) #78 was the rebuild when pointed at this branch. So thank you @deschuma ! We didn't notice this until recently because we were doing maintenance work.

Moving forwards we are going to be having e2e on every PR, linux is completed currently and windows is on the way from our friend @rs--. Which will close this gap completely!

**Comment by BRMcLaren** [comment]
Thanks @ryanhsu19 for the late-night review.

Thanks @deschuma, merging now. @anakrish I am removing the do not merge label due to this having been tested.

**Comment by BRMcLaren** [comment]
bors try

**Pull request merged**
