### PR TITLE
Update snmalloc to 0.6.2

### PR DESCRIPTION
**Pull request by mjp41**
This updates snmalloc to the latest version.

The release includes the updates that remove some levels of thread caching for small heaps.

### CODE REVIEW

**Comment by mjp41** [comment]
@achamayou @daviddesberg

**Comment by achamayou** [comment]
bors try

**Comment by radhikaj** [comment]
@mjp41 @achamayou  - I see these tests failing on Linux and Windows

	311 - tests/stack_overflow_exception (SEGFAULT)

	312 - tests/stack_overflow_exception_unsigned (SEGFAULT)

**Comment by radhikaj** [comment]
bors try

**Comment by achamayou** [comment]
bors try

**Comment by mjp41** [comment]
I have expanded the stack size, which fixed the test failure locally.

Locally, I required
*  5 pages for RelWithDebInfo
*  7 pages for Debug

I have changed to 16.  This is still significantly smaller than any other test.  The following table comes from: `grep -r ../tests/ -e "NumStackPages="`

| test count | number of stack pages | comment
|-------|-----------------------|--------
|     1 | 0                     | `tests/eeid_plugin/enc/enc.conf`
|     1 | 4                     | `tests/stack_overflow_exception/enc/sign.conf`
|     1 | 128                   | `tests/secure_verify/enc/enc.conf`
|     1 | 512                   | `tests/props/enc/sign.conf:`
|    17 | 1024                  | Most tests

The run time for the test is not noticeably changed by using 16 over 8: the tight loop allocating on the stack is insignificant in comparison to starting an enclave.

**Comment by achamayou** [comment]
The testcase failure is happening on a configuration that does make use of snmalloc:

image

in a test that has not been modified in this PR (https://openenclaveci.westus.cloudapp.azure.com/job/OpenEnclave/job/Azure-Linux/586/execution/node/99/log/):

```
The following tests FAILED:
	350 - tests/create-rapid (Timeout)
```

**Comment by achamayou** [comment]
bors try

**Comment by mjp41** [comment]
@radhikaj could this be related to #3108? This seems to imply the test is unreliable.  But failing twice in rapid succession seems suspicious.  Is it?

**Comment by achamayou** [comment]
bors try

**Review by anakrish — APPROVED** [review]
LGTM.

Thanks for the performance improvements!

**Comment by anakrish** [comment]
bors try

**Review by radhikaj — APPROVED** [review]

**Comment by radhikaj** [comment]
Bors r+

**Pull request merged**
