### PR TITLE
Bump Mbed TLS to 2.16.1 LTS

### LINKED ISSUE #1457: Evaluate moving to mbedTLS v2.16 branch
mbedTLS has designated its latest update [v2.16.1](https://tls.mbed.org/download/start/mbedtls-2.16.1-apache.tgz) as of 2018-12-21 the new long-term stable production branch. We should evaluate the impact of moving to this new release:

- [ ] Reconcile breaking changes in the API surface with OE SDK use
- [ ] Evaluate whether this poses issues for link-time mbedTLS replacement for projects using mbedTLS updated with Everest TLS crypto.
- [ ] Evaluate cost-benefit of moving to 2.16.x
- [x] Determine if 2.7 branch is being EOL and timeframe for that.
- [ ] Request OSS SDL security review of new mbedTLS version.

### PR DESCRIPTION
**Pull request by vlaza**
Fixes #1457 by upgrading Mbed TLS to 2.16 LTS branch

### CODE REVIEW

**Comment by johnkord** [comment]
Let's hold off on this until the IO feature branch gets merged into master.

**Comment by vlaza** [comment]
@johnkord I've already tagged "do not merge" as I am still discovering issues with bumping to 2.16.x branch that need to be addressed; this PR will be updated a few more times before it's ready.

**Comment by vlaza** [comment]
I have updated the PR with the following changes:
* Mbed TLS 2.16.1 LTS
* rebase on top of latest master changes

**Comment by CodeMonkeyLeet** [comment]
Per @mikbras, this should not affect his devices changeset and can be merged to master:

> 	#1716 Merging this seems fine to me. The changes are restricted to mbedtls.

**Comment by vlaza** [comment]
@CodeMonkeyLeet @mikbras There are still issues with this bump, things get worse specially after the commit below:

_commit 216b837277331c566b1c3437367469cb402e4e64 (master)
Merge: 4484d5332 4be928c03
Author: oe-bors[bot] <oeciteam@microsoft.com>
Date:   Mon Jun 3 16:52:57 2019 +0000_

Previous to this commit we had failing tests and the list has been published in #1457 
For clarity I will publish them again here also:

```
     14 - tests/mbed/asn1write (Child aborted)           # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     15 - tests/mbed/base64 (Child aborted)              # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     16 - tests/mbed/ccm (Child aborted)                 # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     17 - tests/mbed/cipher.aes (Child aborted)          # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     18 - tests/mbed/cipher.ccm (Child aborted)          # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     19 - tests/mbed/cipher.des (Child aborted)          # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     20 - tests/mbed/cipher.gcm (Child aborted)          # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     21 - tests/mbed/cipher.padding (Child aborted)      # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     22 - tests/mbed/cmac (Child aborted)                # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     23 - tests/mbed/ctr_drbg (Child aborted)            # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     24 - tests/mbed/debug (Child aborted)               # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     25 - tests/mbed/des (Child aborted)                 # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     27 - tests/mbed/ecdsa (Child aborted)               # Test failed: ../tests/mbed/host/host.c(85): Test args.total > args.skipped
     28 - tests/mbed/ecp (Child aborted)                 # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     29 - tests/mbed/entropy (Child aborted)             # Test failed: ../tests/mbed/host/host.c(85): Test args.total > args.skipped
     30 - tests/mbed/error (Child aborted)               # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     31 - tests/mbed/gcm.aes128_en (Child aborted)       # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     32 - tests/mbed/gcm.aes192_en (Child aborted)       # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     33 - tests/mbed/gcm.aes256_en (Child aborted)       # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     34 - tests/mbed/gcm.aes128_de (Child aborted)       # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     35 - tests/mbed/gcm.aes192_de (Child aborted)       # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     36 - tests/mbed/gcm.aes256_de (Child aborted)       # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     37 - tests/mbed/hmac_drbg.misc (Child aborted)      # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     38 - tests/mbed/hmac_drbg.no_reseed (Child aborted) # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     39 - tests/mbed/hmac_drbg.nopr (Child aborted)      # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     40 - tests/mbed/hmac_drbg.pr (Child aborted)        # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     42 - tests/mbed/mdx (Child aborted)                 # Test failed: ../tests/mbed/host/host.c(85): Test args.total > args.skipped
     43 - tests/mbed/mpi (Child aborted)                 # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     44 - tests/mbed/pem (Child aborted)                 # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     45 - tests/mbed/pkcs1_v15 (Child aborted)           # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     46 - tests/mbed/pkcs1_v21 (Child aborted)           # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     47 - tests/mbed/pkcs5 (Child aborted)               # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     48 - tests/mbed/pk (Child aborted)                  # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     49 - tests/mbed/pkparse (Child aborted)             # Test failed: ../tests/mbed/host/host.c(85): Test args.total > args.skipped
     50 - tests/mbed/shax (Child aborted)                # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     51 - tests/mbed/ssl (Child aborted)                 # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     52 - tests/mbed/rsa (Child aborted)                 # Test failed: ../tests/mbed/host/host.c(85): Test args.total > args.skipped
     53 - tests/mbed/version (Child aborted)             # OE_UNSUPPORTED[../tests/mbed/enc/enc.c _syscall_hook:152]
     54 - tests/mbed/x509parse (Child aborted)           # Test failed: ../tests/mbed/host/host.c(85): Test args.total > args.skipped
```

**Comment by anitagov** [comment]
@ionutbalutoiu @vlaza @aserdean - Wondering what the status of this is right now as Mike's devices PR went into master? Do you still have these syscall failures? 
@mikbras - I do not see any changes to use the new syscall hooks in the mbed tests. Do you plan to get those changes into master anytime?

**Comment by vlaza** [comment]
@anitagov There still is work in progress by @aserdean ; we still experience failures

**Comment by anitagov** [comment]
cc: @aserdean 
@vlaza - Thanks for your update. This did not make it into Release 0.6.
Once PR #1960 and one or more related PRs to the mbedtls tests are merged to master, this should be again rebased and retried. Hoping that things will get cleaner then.

**Comment by ionutbalutoiu** [comment]
> cc: @aserdean
> @vlaza - Thanks for your update. This did not make it into Release 0.6.
> Once PR #1960 and one or more related PRs to the mbedtls tests are merged to master, this should be again rebased and retried. Hoping that things will get cleaner then.

Thank-you for the notice @anitagov!

We will keep an eye on PR https://github.com/openenclave/openenclave/pull/1960.

**Comment by anitagov** [comment]
I thought about this some more and don't see why this PR should wait for PR #1960 . The mbed test itself hasn't been modified with the new syscall stuff (see my new Issue #1975 ).

Please point me to the failing pipelines and I will help triage this. Once it is clean, we can try to get this unblocked and into master. MBEDTLS in master is a tad old (revision 2.7.9).

**Comment by ionutbalutoiu** [comment]
> I thought about this some more and don't see why this PR should wait for PR #1960 . The mbed test itself hasn't been modified with the new syscall stuff (see my new Issue #1975 ).
> 
> Please point me to the failing pipelines and I will help triage this. Once it is clean, we can try to get this unblocked and into master. MBEDTLS in master is a tad old (revision 2.7.9).

Hello @anitagov! This is the [most recent CI run](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/1541/pipeline) that we did.

It's a run against [this branch](https://github.com/EmilAlexandruStoica/openenclave/commits/mbedtls-test), and it contains the commits with the Mbed TLS upgrade from this pull request, and [this commit](https://github.com/EmilAlexandruStoica/openenclave/commit/65d19094fb5fc5df8494eb7b9da9b1a645b474cf) to fix some Linux build error.

**Comment by CodeMonkeyLeet** [comment]
@ionutbalutoiu Be aware that this looks like it will interact with upcoming PR for #1893 which introduces new tests that may also have failures against 2.16

**Comment by yakman2020** [comment]
depends on windows syscall support.

**Comment by CodeMonkeyLeet** [comment]
Superseded by #2043

**Pull request closed without merging**
