### PR TITLE
add experimental testing to CI

### PR DESCRIPTION
**Pull request by BRMcLaren**
Add experimental flag in CI to validate experimental features.

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by anakrish** [comment]
This is a great addition! Experimental features ought to be built and locked down with CI.
Experimental features that don't have tests and are not built in CI, are best maintained elsewhere; not in OE SDK master.

**Comment by BRMcLaren** [comment]
> Experimental features that don't have tests and are not built in CI, are best maintained elsewhere; not in OE SDK master.

That seems completely reasonable. I was thinking of having an "experimental branch" such as how we do release versioning, what are your thoughts on this?

**Comment by anakrish** [comment]
> > Experimental features that don't have tests and are not built in CI, are best maintained elsewhere; not in OE SDK master.
> 
> That seems completely reasonable. I was thinking of having an "experimental branch" such as how we do release versioning, what are your thoughts on this?

That's a nice idea. Definitely worth trying out.

**Comment by letmaik** [comment]
Can this be merged?

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
@letmaik @jxyang @wintersteiger 
Please find logs here: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/989/pipeline
Can you please investigate? then we can merge this.

FAILED: enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid.c.o 

/usr/local/lvi-mitigation/bin/clang-7 -DMBEDTLS_CONFIG_FILE="<config.h>" -DOE_API_VERSION=2 -DOE_BUILD_ENCLAVE -DOE_LINK_SGX_DCAP_QL -Ienclave/core -I../3rdparty/mbedtls/mbedtls/include -I3rdparty/mbedtls -I../include -Ioutput/include -Ioutput/include/openenclave/libc -O3 -DNDEBUG   -mllvm -x86-speculative-load-hardening -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -Wno-type-limits -mxsave -no-integrated-as -Wa,-mlfence-before-indirect-branch=register -Wa,-mlfence-before-ret=not -m64 -fPIE -nostdinc -fstack-protector-strong -fvisibility=hidden -fno-omit-frame-pointer -ffunction-sections -fdata-sections -ftls-model=local-exec -fno-builtin-malloc -fno-builtin-calloc -fno-builtin -std=gnu11 -MD -MT enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid.c.o -MF enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid.c.o.d -o enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid.c.o   -c ../common/sgx/eeid.c

../common/sgx/eeid.c:38:50: error: unknown type name 'oe_eeid_t'; did you mean 'oe_uuid_t'?

oe_result_t oe_create_eeid_sgx(size_t data_size, oe_eeid_t** eeid)

                                                 ^~~~~~~~~

                                                 oe_uuid_t

../include/openenclave/bits/evidence.h:46:3: note: 'oe_uuid_t' declared here

} oe_uuid_t;

  ^

../common/sgx/eeid.c:46:27: error: use of undeclared identifier 'oe_eeid_t'

    *eeid = calloc(sizeof(oe_eeid_t) + data_size + signature_size, 1);

                          ^

../common/sgx/eeid.c:49:14: error: no member named 'signature_size' in 'struct _oe_uuid_t'

    (*eeid)->signature_size = signature_size;

    ~~~~~~~  ^

../common/sgx/eeid.c:50:14: error: no member named 'data_size' in 'struct _oe_uuid_t'

    (*eeid)->data_size = data_size;

    ~~~~~~~  ^

../common/sgx/eeid.c:130:37: error: unknown type name 'oe_eeid_t'; did you mean 'oe_uuid_t'?

oe_result_t oe_serialize_eeid(const oe_eeid_t* eeid, char* buf, size_t buf_size)

                                    ^~~~~~~~~

                                    oe_uuid_t

../include/openenclave/bits/evidence.h:46:3: note: 'oe_uuid_t' declared here

} oe_uuid_t;

  ^

../common/sgx/eeid.c:144:26: error: no member named 'version' in 'struct _oe_uuid_t'

        (uint8_t*)&eeid->version,

                   ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:145:22: error: no member named 'version' in 'struct _oe_uuid_t'

        sizeof(eeid->version)));

               ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:150:25: error: no member named 'hash_state' in 'struct _oe_uuid_t'

        (uint8_t*)eeid->hash_state.H,

                  ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:151:22: error: no member named 'hash_state' in 'struct _oe_uuid_t'

        sizeof(eeid->hash_state.H)));

               ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:156:25: error: no member named 'hash_state' in 'struct _oe_uuid_t'

        (uint8_t*)eeid->hash_state.N,

                  ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:157:22: error: no member named 'hash_state' in 'struct _oe_uuid_t'

        sizeof(eeid->hash_state.N)));

               ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:162:26: error: no member named 'signature_size' in 'struct _oe_uuid_t'

        (uint8_t*)&eeid->signature_size,

                   ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:163:22: error: no member named 'signature_size' in 'struct _oe_uuid_t'

        sizeof(eeid->signature_size)));

               ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:168:26: error: no member named 'size_settings' in 'struct _oe_uuid_t'

        (uint8_t*)&eeid->size_settings,

                   ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:169:22: error: no member named 'size_settings' in 'struct _oe_uuid_t'

        sizeof(eeid->size_settings)));

               ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:174:26: error: no member named 'data_size' in 'struct _oe_uuid_t'

        (uint8_t*)&eeid->data_size,

                   ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:175:22: error: no member named 'data_size' in 'struct _oe_uuid_t'

        sizeof(eeid->data_size)));

               ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:180:26: error: no member named 'vaddr' in 'struct _oe_uuid_t'

        (uint8_t*)&eeid->vaddr,

                   ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

../common/sgx/eeid.c:181:22: error: no member named 'vaddr' in 'struct _oe_uuid_t'

        sizeof(eeid->vaddr)));

               ~~~~  ^

../include/openenclave/internal/raise.h:167:33: note: expanded from macro 'OE_CHECK'

        oe_result_t _result_ = (EXPRESSION); \

                                ^~~~~~~~~~

fatal error: too many errors emitted, stopping now [-ferror-limit=]

20 errors generated.

[864/4831] /usr/local/lvi-mitigation/bin/clang-7 -DMBEDTLS_CONFIG_FILE="<config.h>" -DOE_API_VERSION=2 -DOE_BUILD_ENCLAVE -DOE_LINK_SGX_DCAP_QL -Ienclave/core -I../3rdparty/mbedtls/mbedtls/include -I3rdparty/mbedtls -I../include -Ioutput/include -Ioutput/include/openenclave/libc -O3 -DNDEBUG   -mllvm -x86-speculative-load-hardening -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -Wno-type-limits -mxsave -no-integrated-as -Wa,-mlfence-before-indirect-branch=register -Wa,-mlfence-before-ret=not -m64 -fPIE -nostdinc -fstack-protector-strong -fvisibility=hidden -fno-omit-frame-pointer -ffunction-sections -fdata-sections -ftls-model=local-exec -fno-builtin-malloc -fno-builtin-calloc -fno-builtin -std=gnu11 -MD -MT enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid_verifier.c.o -MF enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid_verifier.c.o.d -o enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid_verifier.c.o   -c ../common/sgx/eeid_verifier.c

FAILED: enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid_verifier.c.o 

/usr/local/lvi-mitigation/bin/clang-7 -DMBEDTLS_CONFIG_FILE="<config.h>" -DOE_API_VERSION=2 -DOE_BUILD_ENCLAVE -DOE_LINK_SGX_DCAP_QL -Ienclave/core -I../3rdparty/mbedtls/mbedtls/include -I3rdparty/mbedtls -I../include -Ioutput/include -Ioutput/include/openenclave/libc -O3 -DNDEBUG   -mllvm -x86-speculative-load-hardening -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -Wno-type-limits -mxsave -no-integrated-as -Wa,-mlfence-before-indirect-branch=register -Wa,-mlfence-before-ret=not -m64 -fPIE -nostdinc -fstack-protector-strong -fvisibility=hidden -fno-omit-frame-pointer -ffunction-sections -fdata-sections -ftls-model=local-exec -fno-builtin-malloc -fno-builtin-calloc -fno-builtin -std=gnu11 -MD -MT enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid_verifier.c.o -MF enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid_verifier.c.o.d -o enclave/CMakeFiles/oeenclave-lvi-cfg.dir/__/common/sgx/eeid_verifier.c.o   -c ../common/sgx/eeid_verifier.c

../common/sgx/eeid_verifier.c:252:5: error: use of undeclared identifier 'oe_eeid_t'; did you mean 'oe_exit'?

    oe_eeid_t *attester_eeid = NULL, *verifier_eeid = NULL;

    ^~~~~~~~~

    oe_exit

../include/openenclave/corelibc/stdlib.h:55:19: note: 'oe_exit' declared here

OE_NO_RETURN void oe_exit(int status);

                  ^

../common/sgx/eeid_verifier.c:252:16: error: use of undeclared identifier 'attester_eeid'

    oe_eeid_t *attester_eeid = NULL, *verifier_eeid = NULL;

               ^

../common/sgx/eeid_verifier.c:252:39: error: use of undeclared identifier 'verifier_eeid'

    oe_eeid_t *attester_eeid = NULL, *verifier_eeid = NULL;

                                      ^

../common/sgx/eeid_verifier.c:253:5: error: use of undeclared identifier 'oe_eeid_evidence_t'; did you mean 'oe_get_evidence'?

    oe_eeid_evidence_t* evidence = NULL;

    ^~~~~~~~~~~~~~~~~~

    oe_get_evidence

../include/openenclave/attestation/attester.h:104:13: note: 'oe_get_evidence' declared here

oe_result_t oe_get_evidence(

            ^

../common/sgx/eeid_verifier.c:253:25: error: use of undeclared identifier 'evidence'

    oe_eeid_evidence_t* evidence = NULL;

                        ^

../common/sgx/eeid_verifier.c:259:5: error: use of undeclared identifier 'evidence'

    evidence = oe_malloc(evidence_buffer_size);

    ^

../common/sgx/eeid_verifier.c:261:9: error: implicit declaration of function 'oe_eeid_evidence_ntoh' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

        oe_eeid_evidence_ntoh(evidence_buffer, evidence_buffer_size, evidence));

        ^

../common/sgx/eeid_verifier.c:261:70: error: use of undeclared identifier 'evidence'

        oe_eeid_evidence_ntoh(evidence_buffer, evidence_buffer_size, evidence));

                                                                     ^

../common/sgx/eeid_verifier.c:263:32: error: use of undeclared identifier 'evidence'

    sgx_evidence_buffer_size = evidence->sgx_evidence_size;

                               ^

../common/sgx/eeid_verifier.c:264:36: error: use of undeclared identifier 'evidence'

    sgx_endorsements_buffer_size = evidence->sgx_endorsements_size;

                                   ^

../common/sgx/eeid_verifier.c:265:24: error: use of undeclared identifier 'evidence'

    eeid_buffer_size = evidence->eeid_size;

                       ^

../common/sgx/eeid_verifier.c:266:19: error: use of undeclared identifier 'evidence'

    eeid_buffer = evidence->data + evidence->sgx_evidence_size +

                  ^

../common/sgx/eeid_verifier.c:266:36: error: use of undeclared identifier 'evidence'

    eeid_buffer = evidence->data + evidence->sgx_evidence_size +

                                   ^

../common/sgx/eeid_verifier.c:267:19: error: use of undeclared identifier 'evidence'

                  evidence->sgx_endorsements_size;

                  ^

../common/sgx/eeid_verifier.c:277:37: error: use of undeclared identifier 'evidence'

        memcpy(sgx_evidence_buffer, evidence->data, sgx_evidence_buffer_size);

                                    ^

../common/sgx/eeid_verifier.c:287:13: error: use of undeclared identifier 'evidence'

            evidence->data + evidence->sgx_evidence_size,

            ^

../common/sgx/eeid_verifier.c:287:30: error: use of undeclared identifier 'evidence'

            evidence->data + evidence->sgx_evidence_size,

                             ^

../common/sgx/eeid_verifier.c:293:9: error: use of undeclared identifier 'attester_eeid'

        attester_eeid = oe_memalign(2 * sizeof(void*), eeid_buffer_size);

        ^

../common/sgx/eeid_verifier.c:294:14: error: use of undeclared identifier 'attester_eeid'

        if (!attester_eeid)

             ^

fatal error: too many errors emitted, stopping now [-ferror-limit=]

20 errors generated.

[865/4831] /usr/local/lvi-mitigation/bin/clang++-7  -DLIBCXXRT -DOE_API_VERSION=2 -DOE_BUILD_ENCLAVE -DOE_LIBC_SUPPRESS_DEPRECATIONS -DOE_LINK_SGX_DCAP_QL -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE -I../3rdparty/libcxx/libcxx/src -I../3rdparty/libcxx/../libcxxrt/libcxxrt/src -I../include -Ioutput/include -Ioutput/include/openenclave/libcxx -Ioutput/include/openenclave/libc -O3 -DNDEBUG   -mllvm -x86-speculative-load-hardening -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -Wno-type-limits -mxsave -no-integrated-as -Wa,-mlfence-before-indirect-branch=register -Wa,-mlfence-before-ret=not -Wno-error -m64 -fPIE -nostdinc -fstack-protector-strong -fvisibility=hidden -fno-omit-frame-pointer -ffunction-sections -fdata-sections -ftls-model=local-exec -fno-builtin-malloc -fno-builtin-calloc -fno-builtin -nostdinc++ -std=c++14 -MD -MT 3rdparty/libcxx/CMakeFiles/libcxx-lvi-cfg.dir/libcxx/src/locale.cpp.o -MF 3rdparty/libcxx/CMakeFiles/libcxx-lvi-cfg.dir/libcxx/src/locale.cpp.o.d -o 3rdparty/libcxx/CMakeFiles/libcxx-lvi-cfg.dir/libcxx/src/locale.cpp.o -c ../3rdparty/libcxx/libcxx/src/locale.cpp

../3rdparty/libcxx/libcxx/src/locale.cpp:4237:12: warning: implicit conversion loses integer precision: 'int' to 'char' [-Wconversion]

    dest = res;

         ~ ^~~

1 warning generated.

ninja: build stopped: subcommand failed.

script returned exit code 1

**Comment by wintersteiger** [comment]
Build scripts are fixed in #3293

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
Thanks @wintersteiger

**Comment by radhikaj** [comment]
Will wait for #3293 to be merged and then merge this.

**Comment by BRMcLaren** [comment]
bor r+

**Pull request merged**
