### PR TITLE
Update dcap version to 1.10 for windows

### PR DESCRIPTION
**Pull request by qiucwang**
Install Azure DCAP Client 1.10.0 NuGet package which uses V3 collateral for default.

Signed-off-by: Qiucheng Wang <qiucwang@microsoft.com>

### CODE REVIEW

**Review by mingweishih — APPROVED** [review]

**Comment by mingweishih** [comment]
@rs--  @CyanDevs please check and see if we need re-imaging.

**Comment by rs--** [comment]
Running it through e2e now

**Review by yentsanglee — APPROVED** [review]

**Comment by yentsanglee** [comment]
bors try

**Comment by yentsanglee** [comment]
@rs-- @CyanDevs Does this look OK to be merged?

**Review by rs-- — APPROVED** [review]

**Pull request merged**
