### PR TITLE
Tentative update to dependabot to only allow releases of snmalloc

### PR DESCRIPTION
**Pull request by achamayou**
Suggested in #4443

### CODE REVIEW

**Review by dthaler — APPROVED** [review]
I don't know if this change is correct or not, but I have no objections if this does work.

**Comment by anakrish** [comment]
@CyanDevs Can you also review this PR?

**Comment by CyanDevs** [comment]
Thanks for making this change @achamayou. Could you amend your commit with the DCO? Also, did you intentionally exclude semver-major in this PR?

**Comment by achamayou** [comment]
@CyanDevs I have done that now. I think we don't want automatic semver-major because it's very unlikely to work out of the box, and is likely to require careful manual input? Happy to change that if not though.

**Review by radhikaj — APPROVED** [review]
bors r+

**Pull request merged**
