### PR TITLE
Switch to clang-11 as default OE SDK compiler

### PR DESCRIPTION
**Pull request by anakrish**

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by radhikaj** [comment]
closing since this has successfully been completed. Thanks for your pioneering work, @anakrish

**Pull request closed without merging**
