### PR TITLE
Fix the switchless ECALL fallback path

### PR DESCRIPTION
**Pull request by mingweishih**
This PR fixes a bug such that a switchless ECALL will behave like a regular ECALL when the enclave is created without switchless settings. Also, adding tests to the existing switchless test case.

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

**Review by anakrish — APPROVED** [review]
Thanks!

**Review by radhikaj — APPROVED** [review]
Thanks @mingweishih

**Comment by radhikaj** [comment]
Bors r+

**Pull request merged**
