### PR TITLE
enable 0-base tests by default

### PR DESCRIPTION
**Pull request by RRathna**
Signed-off-by: Rathna Ramesh <rathna1993@gmail.com>

### CODE REVIEW

**Review by mingweishih — APPROVED** [review]

**Review by CyanDevs — APPROVED** [review]

**Comment by CyanDevs** [comment]
0-base tests in simulation mode failed with the following
```

Could not create enclave, result=3

2021-07-20T00:28:41+0000.933417Z [(H)ERROR] tid(0x7f4567a27740) | Requested creation of 0-base enclave in simulation mode, which is currently not supported.

 [../host/sgx/create.c:oe_sgx_build_enclave:929]

2021-07-20T00:28:41+0000.933430Z [(H)ERROR] tid(0x7f4567a27740) | :OE_INVALID_PARAMETER [../host/sgx/create.c:oe_sgx_build_enclave:930]

2021-07-20T00:28:41+0000.933618Z [(H)ERROR] tid(0x7f4567a27740) | :OE_INVALID_PARAMETER [../host/sgx/create.c:oe_create_enclave:1207]
```

Do we want to skip the 0-base tests when we're in simulation mode?

**Comment by anakrish** [comment]
Yes. 0-base test ought to be disabled in simulation mode.
Once this test is enabled by default, what is the user experience when OE SDK is built from source on a machine that does not have enclave_create_ex support?

**Comment by RRathna** [comment]
> Yes. 0-base test ought to be disabled in simulation mode.
> Once this test is enabled by default, what is the user experience when OE SDK is built from source on a machine that does not have enclave_create_ex support?

If in OE_SET_ENCLAVE_SGX2() the user sets CREATE_ZERO_BASE_ENCLAVE=1, and the enclave_create_ex() cannot be found in the sgx_enclave_common.so.1, then the following happens:

```
2021-06-30T02:07:40+0000.238811Z [(H)ERROR] tid(0x7fdbcb234740) | enclave_create_ex function not found.
1: [/home/ratrames/dev/OE_0_base/host/sgx/sgx_enclave_common_wrapper.c:_lookup_function:110]
1: 2021-06-30T02:07:40+0000.238819Z [(H)ERROR] tid(0x7fdbcb234740) | enclave_create_ex() was not found in installed libsgx_enclave_common.so.1. [/home/ratrames/dev/OE_0_base/host/sgx/sgx_enclave_common_wrapper.c:oe_sgx_enclave_create_ex:202]
1: 2021-06-30T02:07:40+0000.238821Z [(H)ERROR] tid(0x7fdbcb234740) | enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0) (oe_result_t=OE_PLATFORM_ERROR) [/home/ratrames/dev/OE_0_base/host/sgx/sgxload.c:oe_sgx_create_enclave:441]
1: 2021-06-30T02:07:40+0000.238822Z [(H)ERROR] tid(0x7fdbcb234740) | :OE_PLATFORM_ERROR [/home/ratrames/dev/OE_0_base/host/sgx/create.c:oe_sgx_build_enclave:964]
1: 2021-06-30T02:07:40+0000.238962Z [(H)ERROR] tid(0x7fdbcb234740) | :OE_PLATFORM_ERROR [/home/ratrames/dev/OE_0_base/host/sgx/create.c:oe_create_enclave:1204]
```

**Comment by RRathna** [comment]
Enabled test/sgx_zerobase as part of #4162.

**Pull request closed without merging**
