### PR TITLE
Add Support of Interoperable TLS Proposal

### PR DESCRIPTION
**Pull request by shnwc**
The design is documented in file Interoperable-Attested-TLS.md

### CODE REVIEW

**Review by radhikaj — APPROVED** [review]

**Comment by radhikaj** [comment]
@MWShan @mingweishih , can you please review? Thanks

**Review by MWShan — APPROVED** [review]

**Comment by radhikaj** [comment]
thanks @shnwc

**Comment by dimakuv** [comment]
Hello, I see that the design document for [Interoperable RA-TLS](https://github.com/ccc-attestation/interoperable-ra-tls) was merged, but I don't see any PR/commits for the actual implementation of Interoperable RA-TLS in OpenEnclave. Is there a plan to add this feature? If yes, then what is the timeline?

**Pull request merged**
