### PR TITLE
Deprecate Ubuntu 16.04 in CI

### PR DESCRIPTION
**Pull request by CyanDevs**
This is a prerequisite for merging #3832 
Signed-off-by: Chris Yan <chrisyan@microsoft.com>

### CODE REVIEW

**Comment by CyanDevs** [comment]
@rs-- could you please review? Thanks!

**Review by rs-- — APPROVED** [review]

**Comment by CyanDevs** [comment]
bors try

**Review by radhikaj — APPROVED** [review]

**Comment by mingweishih** [comment]
bors delegate=CyanDevs

**Pull request merged**
