### PR TITLE
Use GCC (GNU) atomic builtins for acquire-release

### PR DESCRIPTION
**Pull request by anakrish**
This will emit the right instructions for all platforms.

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
> We also need definitions for these 2 commonly used memory orders: __ATOMIC_ACQ_REL and __ATOMIC_SEQ_CST

These are GCC/Clang builtins. We don't need to redefine them..

**Comment by andschwa** [comment]
@anakrish This commit was authored by "Ubuntu"...

**Pull request merged**
