### PR TITLE
Remove RHEL support in CI

### PR DESCRIPTION
**Pull request by rs--**

### CODE REVIEW

**Comment by rs--** [comment]
bors try

**Comment by rs--** [comment]
bors try

**Comment by rs--** [comment]
bors try

**Comment by rs--** [comment]
bors try

**Review by CyanDevs — APPROVED** [review]
Looks good, thanks!

**Review by radhikaj — APPROVED** [review]
Bors r+

**Review by anakrish — APPROVED** [review]

**Comment by rs--** [comment]
bors cancel

**Pull request merged**
