### PR TITLE
update windows to 2.7 PSW and 1.5 DCAP

### PR DESCRIPTION
**Pull request by BRMcLaren**

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by CodeMonkeyLeet** [comment]
@radhikaj WindowsManualInstallPrereqs.md has outdated references to the 2.6 version number but has no functional impact. We should fix that up separately since this is being merged already.

**Comment by radhikaj** [comment]
V1.5 of Intel DCAP does not have NuGet packages that the install prereqs script expects. Lets wait to merge this.

**Pull request merged**
