### PR TITLE
add and integrate intel ci triggers to nightly builds

### PR DESCRIPTION
**Pull request by BRMcLaren**
Integrate Intel CI into the nightly builds. Use managed jenkinsoperator image for trigger for versioning maintained in the test-infra repo. Do not trigger on pull requests as we do not have their Jenkinsfiles integrated, to not block other PR's.

Signed-off-by: brmclare <brmclare@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
Manual run, as we are not integrating PR testing. Ensure the following passes, before merge.

https://oe-jenkins-dev.westeurope.cloudapp.azure.com/job/pipelines/job/Intel-Agnostic/44/

**Review by radhikaj — APPROVED** [review]
Can you add a comment to say that the image needs to be updated everytime the script is updated?

**Comment by BRMcLaren** [comment]
> Can you add a comment to say that the image needs to be updated everytime the script is updated?

This is a good catch, thanks. I have added a simple maintenance guide to the PR.

**Review by rs-- — APPROVED** [review]

**Pull request merged**
