### PR TITLE
disable code coverage test temporarily

### PR DESCRIPTION
**Pull request by BRMcLaren**
Signed-off-by: Brett McLaren <brmclare@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/job/Sandbox/112/ *fingers crossed*

**Review by nonpolarity — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]

**Pull request merged**
