### PR TITLE
Jenkins Maintenence

### LINKED ISSUE #3488: Bors takes 4 hours to timeout a failed build
This a clean up request. 

Earlier this year the OE project did not have enough hardware to accommodate the testing suites, the solution was to allow for longer testing suites (4 hours). We haven't seen a legitimate (possible to complete) build take longer than an hour in a few months, suggest lowering the timeout time to not extend the queue time unnecessarily.

### PR DESCRIPTION
**Pull request by BRMcLaren**
Doing maintenance work to cut down on flakey testing. Sourced as one PR to allow testing all changes together. 

This PR:

Lowers Jenkins global timeout testing.

> If a CI machine freezes or finds code that will not complete the timeout is lowered from 4 hours to 2 hour, this allows other developers to not need to wait 4+ hours in queue. Fixes #3488

Add retry loop to ansible within Jenkins files

> Some good points made here: https://github.com/openenclave/openenclave/pull/3259 regarding idempotency and implementation. This change is mainly focusing on the package installation at the Jenkins level, to cut down on long network timeouts

Signed-off-by: Brett McLaren <brmclare@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/job/Sandbox/

63 - 67, not including 64

**Comment by BRMcLaren** [comment]
85-90

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Review by rs-- — APPROVED** [review]

**Comment by BRMcLaren** [comment]
bors try

**Review by radhikaj — APPROVED** [review]
Thanks!

**Pull request merged**
