### PR TITLE
Add Win2019 to Nightly Tests

### PR DESCRIPTION
**Pull request by rs--**
- Store nightly build packages in branch specific paths

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by mingweishih** [comment]
@rs--  @BRMcLaren  @ionutbalutoiu Is this PR intended for the branch v0.9.x rather than master?

**Comment by rs--** [comment]
@mingweishih  The original intension was the v0.9.x nightly pipeline, so I'm okay with it going to the v0.9.x branch for now and eventually making its way into master.

**Comment by mingweishih** [comment]
> @mingweishih The original intension was the v0.9.x nightly pipeline, so I'm okay with it going to the v0.9.x branch for now and eventually making its way into master.

Thanks for the clarification.

**Comment by BRMcLaren** [comment]
Hello @rs--, regarding the comment above wanted to check if you are going to be setting up an independent PR to merge into master?

The reason for this is that v0.9.x will never be merged into master as we use "Release Branching" and more information can be found here: https://www.atlassian.com/agile/software-development/branching

**Comment by BRMcLaren** [comment]
Ah, Bors is failing due to a protected branch.

Can we please change the target of this PR to master and we will let our release manager integrate as needed?

**Comment by radhikaj** [comment]
#2971 is in. Closing this one.

**Pull request closed without merging**
