### PR TITLE
Fix improper size_t type usage

### LINKED ISSUE #3377: OE checks whether a size_t variable is negative
On this [line](https://github.com/openenclave/openenclave/blob/80309da445e768d05031b14ef0e33997662a7769/enclave/crypto/cert.c#L1180), we are checking if a size_t variable `bytes_written` is <= 0.  So even if the function `mbedtls_x509write_crt_der` returns a negative number to indicate error, we will never detect it.

We are lucky that `mbedtls_x509write_crt_der` never failed until today when I tried to generate an EEID based certificate and that triggered `MBEDTLS_ERR_ASN1_BUF_TOO_SMALL`.

### PR DESCRIPTION
**Pull request by larrywxyz**
Fixes #3377

### CODE REVIEW

**Review by CodeMonkeyLeet — APPROVED** [review]

**Review by radhikaj — APPROVED** [review]
Thanks @larrywxyz

**Pull request merged**
