### PR TITLE
Update to use version 1.5.0 of Azure DCAP

### PR DESCRIPTION
**Pull request by deschuma**
Update OE SDK to use the latest version of Azure DCAP which includes changes to:
- Cache additional collateral on the client (not just certificates)
- Add environment variable to enable debug logging

Tested on Ubuntu 16, 18 and Windows Server 2019

### CODE REVIEW

**Comment by anakrish** [comment]
@deschuma Is there no source code update needed on the Linux side ansible scripts?

**Comment by deschuma** [comment]
@anakrish last time this was all that was needed -unless something has changed, I thought Linux side just picked up the latest version

**Comment by jhand2** [comment]
@anakrish we don't specify a version for the package in ansible. The same is true for the libsgx packages. So whenever the apt repo gets updated, we automatically start using it.

Fixing the package versions is an option, but if users do an `apt upgrade` they will get the newest package and rolling back can sometimes be a pain depending on what other packages were also updated on the system.

**Comment by anakrish** [comment]
@jhand2 @deschuma Then its fine.

@yentsanglee @soccerGB Can you please review/approve this PR since this is attestation related?

**Comment by CodeMonkeyLeet** [comment]
@BRMcLaren Does this change need to be tested against the CI/CD infrastructure and the package cache updated?

**Pull request merged**
