### PR TITLE
change required approvers from 1 to 2

### PR DESCRIPTION
**Pull request by BRMcLaren**
Change the required reviewers from 1 to 2.

We should be requiring 2 approvers given cross-collaboration efforts.

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
@andschwa 

I agree with your statement. That being said with the upcoming cross-collaboration efforts, requiring two approvals may be better for stability purposes. Something reasonable would be 2 approvals, at least 1 being a Committer would be a good idea.

It's not a question of trust, in my opinion, it's a question of how fast we are growing and leveraging that extra experience to our advantage by promoting knowledge sharing.

Do you believe this should be brought up with the CGC? We can always revert if it is becoming a major hindrance, I believe the recommended approach right now is to get 2 approvers even if it is not forced by tooling.

**Comment by jhand2** [comment]
I’m also on board with this. Plus the operational burden can be overcome by simply being more intentional about reviewing PRs. Especially small ones that don’t require a lot of time to look into.

**Comment by andschwa** [comment]
> Do you believe this should be brought up with the CGC?

In my opinion, yes.

**Comment by BRMcLaren** [comment]
Sure.

@andschwa @dthaler are both part of the committee and have different viewpoints, could you bring it up at the next meeting and get a vote?

**Comment by andschwa** [comment]
Added to new business!

**Comment by johnkord** [comment]
It may be worthwhile to have two approvals required before merge simply for account security reasons

**Comment by BRMcLaren** [comment]
Thanks, @andschwa !

I had added the do-not-merge label to avoid accidental merging, which I guess we now know works!

Removing label and merging.

bors r+

**Pull request merged**
