### PR TITLE
Enable create-rapid for sgx on windows

### PR DESCRIPTION
**Pull request by mingweishih**
This PR fixes minor issues of the create-rapid for sgx on windows and re-enables the test. The issue with the test is similar to #2394. More specifically, current window environment on ACC allows enclaves to take upto ~31 MB. As a workaround, this PR reduces the memory size per enclave and the number of simultaneous enclaves.

Note: According to my experiment, an enclave with small heap and stack size (4 pages each) takes around 1 MB of EPC. Therefore, the test fails with this configuration when the number of simultaneous enclaves is 32.

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Pull request merged**
