### PR TITLE
increase heap pages and re-enable jenkins snmalloc tests

### PR DESCRIPTION
**Pull request by BRMcLaren**
Signed-off-by: Brett McLaren <brmclare@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
This is the code changes from #3537 to ensure no other breaks.

**Comment by BRMcLaren** [comment]
bors try

**Review by achamayou — APPROVED** [review]

**Review by anakrish — APPROVED** [review]
LGTM

**Pull request merged**
