### PR TITLE
Add dependabot support

### PR DESCRIPTION
**Pull request by dthaler**
Dependabot will automatically file a pull request when there is
a newer version of a dependency available. The principle is
that openenclave should always upgrade to use the latest release of
each dependency whenever possible to get bug fixes and security
patches.

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

### CODE REVIEW

**Comment by radhikaj** [comment]
Thanks for doing this. Each dependabot alert will need to be carefully vetted before merging. Every aspect of CI is not testable via Jenkins currently.

**Review by radhikaj — APPROVED** [review]

**Comment by radhikaj** [comment]
@CyanDevs @rs--  Please comment

**Review by CyanDevs — APPROVED** [review]
Going off of the doc on line 5 this looks fine to me.

I would also want to add the pip and docker package as well as there is value in catching security issues with Docker images and Python packages that we pin to.

**Comment by CyanDevs** [comment]
@dthaler @radhikaj It looks like CI failed this PR for not having the exact match for the license header we usually use.
```
# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.
```
This comes from https://github.com/openenclave/openenclave/blob/master/scripts/check-license#L14

I don't know much about about legal licensing and wording. Should the license wording be changed to match, or add some flexibility in the check-license script?

**Comment by dthaler** [comment]
> @dthaler @radhikaj It looks like CI failed this PR for not having the exact match for the license header we usually use.

Thanks for pointing this out, I hadn't noticed that.  Now fixed.

**Pull request merged**
