### PR TITLE
Remove duplicate OE_WEAK

### PR DESCRIPTION
**Pull request by asvrada**
Signed-off-by: Zijie Wu <zijiewu@microsoft.com>

### CODE REVIEW

**Comment by asvrada** [comment]
bors try

**Review by mingweishih — APPROVED** [review]

**Comment by asvrada** [comment]
bors try

**Review by anakrish — APPROVED** [review]

**Comment by asvrada** [comment]
> Build failed:
> 
> * [continuous-integration/jenkins/branch](https://openenclaveci.westus.cloudapp.azure.com/job/Bors/job/openenclave/job/staging/145/display/redirect)

WHY

**Pull request merged**
