### PR TITLE
add windows simulation mode to ci

### LINKED ISSUE #2614: CI: Enable Windows SGX Simulation mode testing
PR #2600 enables SGX Simulation Mode on Windows.
The CI needs to be updated to lock this down.

### PR DESCRIPTION
**Pull request by BRMcLaren**
Fixes #2614

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
@anakrish That is interesting information!

I think what we want to do as a final solution is to add a switch to the win2016CrossCompile test for simulation and nonsimulation mode. This will reduce code duplication, I can ping you when the PR is ready if you want to double-check the solution.

**Comment by dthaler** [comment]
> OE_SIMULATION=1 does not affect the build process. It only affects the way tests are run.
> Would there be benefit to reusing an existing build?

+1

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bor try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Pull request merged**
