### PR TITLE
Update SDK clang compiler version to 10

### PR DESCRIPTION
**Pull request by manojrupireddy**
* Updating clang compiler to version 10. SDK and samples will be built using clang10.
* Yet to update release notes. 
* Mark as do not merge, till sanity test is done on CI.
Signed-off-by: manoj rupireddy <marupire@microsoft.com>

### CODE REVIEW

**Review by mingweishih — COMMENTED** [review]
Can you also update the changelog and mention that we no longer support building samples with clang-7?

**Review by dthaler — CHANGES_REQUESTED** [review]
You're missing some files.  For example:
devex/vsextension/ProjectTemplates/oeenclave-linux/MyEnclave.vcxproj has
```
<RemoteCCompileToolExe>clang-8</RemoteCCompileToolExe>
```
devex/vsextension/msbuild/open-enclave-cross.targets has
```
<OECompilerPathSegment>clang-8</OECompilerPathSegment>
```
devex/cross-nuget/windows/pack.ps1 has
```
New-Item -ItemType Directory -Path Pack\lib\native\win\sgx\default\debug\enclave\clang-8 | Out-Null
```
etc.

**Review by radhikaj — APPROVED** [review]
Thanks for this PR @manojrupireddy

**Review by dthaler — APPROVED** [review]

**Comment by radhikaj** [comment]
bors try

**Review by achamayou — APPROVED** [review]
Looking forward to this upgrade :)

**Pull request closed without merging**
