### PR TITLE
Add Jordan to CGC in Committers.md

### PR DESCRIPTION
**Pull request by CodeMonkeyLeet**
Per [2/11/2020 CGC meeting](https://hackmd.io/TOJhJXswQ5yfObq1T659ug#February-11-2020), add Jordan to the CGC list in docs/Committers.md.

Signed-off-by: Simon Leet <simon.leet@microsoft.com>

### CODE REVIEW

**Comment by andschwa** [comment]
@CodeMonkeyLeet your commit authorship looks funky.

**Comment by jhand2** [comment]
> @CodeMonkeyLeet your commit authorship looks funky.

@andschwa please speak in concrete problems 😄

Do you mean the markdown in the commit message? If so we should specify how links should be included in the commit message in the [Contributing Guidelines](https://github.com/openenclave/openenclave/blob/master/docs/Contributing.md#commit-messages)

**Comment by andschwa** [comment]
@jhand2 No, I mean Simon's commit is not linking to his GitHub profile, implying that the email address is incorrect and should be fixed.

**Comment by CodeMonkeyLeet** [comment]
@andschwa Thanks for the catch!

**Comment by andschwa** [comment]
No prob ☺️

**Pull request merged**
