### PR TITLE
Updated references (docs and scripts) to use new SGX version

### PR DESCRIPTION
**Pull request by chrisrod-MSFT**
1. Updated scripts and docs that referenced SGX versions to new versions in intel registration center
2. Uploaded and then referenced oejenkins Azure storage container files in scripts.
3. Updated changelog.

### CODE REVIEW

**Comment by chrisrod-MSFT** [comment]
@johnkord does this look about right?

**Comment by jhand2** [comment]
Looks good. We can close #2314 when this PR is merged

**Comment by chrisrod-MSFT** [comment]
I believe we are holding on this PR as samples on Windows are not working. Will provide update as we have more information.

**Comment by chrisrod-MSFT** [comment]
We should be good to go on this. Fresh installs using scripts on ACC VMs (Ubuntu 1604, 1804 and Windows 2016) with all tests passing.  Will need someone in @openenclave/committers to remove the label and merge.

**Pull request merged**
