### PR TITLE
Update Pluggable allocator sample CMakeLists.txt to add cryptolib for linking

### PR DESCRIPTION
**Pull request by radhikaj**

### CODE REVIEW

**Comment by radhikaj** [comment]
bors try

**Review by mingweishih — APPROVED** [review]

**Review by anakrish — APPROVED** [review]

**Review by CyanDevs — APPROVED** [review]

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
bors try-

**Comment by radhikaj** [comment]
bors try

**Comment by anakrish** [comment]
Failure seems to be in attested_tls sample:
```
Host: Requesting enclave_a to generate a targeted evidence with an encryption key

2021-06-17T04:21:46+0000.010757Z [(H)ERROR] tid(0x7f96b7c99f40) | sgxquoteprovider: libdcap_quoteprov.so libdcap_quoteprov.so: cannot open shared object file: No such file or directory

 [../host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:81]

2021-06-17T04:21:46+0000.010766Z [(H)ERROR] tid(0x7f96b7c99f40) | oe_initialize_quote_provider failed (oe_result_t=OE_QUOTE_PROVIDER_LOAD_ERROR) [../host/sgx/sgxquoteprovider.c:oe_initialize_quote_provider:48]

2021-06-17T04:21:46+0000.010768Z [(H)ERROR] tid(0x7f96b7c99f40) | :OE_QUOTE_PROVIDER_LOAD_ERROR [../host/sgx/quote.c:sgx_get_qetarget_info:35]

Host: get_evidence_with_public_key failed. OE_OK

Host: attestation failed with 1

Host: Terminating enclaves

Host: Enclave successfully terminated.

Host: Enclave successfully terminated.

Host:  failed 

make: Leaving directory '/home/oeadmin/workspace/pipelines/Azure-Linux/build/install/opt/openenclave/share/openenclave/samples/attestation'

make: *** [Makefile:27: runsgxremote] Error 1
```

**Pull request merged**
