### PR TITLE
Code changes to enable building OE using VS_buildtools 2019

### PR DESCRIPTION
**Pull request by RRathna**
These code changes enable OE to be built using Visual Studio 2019 buildtools, in windows.

### CODE REVIEW

**Comment by RRathna** [comment]
bors try

**Review by dthaler — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]

**Comment by RRathna** [comment]
bors try

**Comment by RRathna** [comment]
bors try

**Review by radhikaj — CHANGES_REQUESTED** [review]
Rathna, I request you split this into two PRs
1) Allow code to be built in VS 2019. Can be merged right away.
2) Change install-prereqs to install VS2019. I would like to merge this after CI images are updated with VS 2019. That will not be in the next couple of weeks.

**Review by radhikaj — APPROVED** [review]
Thanks Rathna!

**Comment by radhikaj** [comment]
bors try

**Comment by RRathna** [comment]
> ## try
> Build failed:
> 
> * [continuous-integration/jenkins/branch](https://openenclaveci.westus.cloudapp.azure.com/job/Bors/job/openenclave/job/trying/67/display/redirect)

Fails with
'''
Cannot contact ws19-dca1f0000: java.lang.InterruptedException

Could not connect to ws19-dca1f0000 to send interrupt signal to process
'''

**Pull request merged**
