### PR TITLE
Update Jenkinsfiles for migration

### PR DESCRIPTION
**Pull request by CyanDevs**
Signed-off-by: Chris Yan <chrisyan@microsoft.com>

### CODE REVIEW

**Comment by CyanDevs** [comment]
bors try

**Comment by CyanDevs** [comment]
bors try

**Comment by CyanDevs** [comment]
bors try

**Comment by CyanDevs** [comment]
bors try

**Comment by CyanDevs** [comment]
bors try

**Review by radhikaj — APPROVED** [review]

**Comment by CyanDevs** [comment]
bors try

**Review by RRathna — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]

**Comment by CyanDevs** [comment]
bors r+

Some VMs had network issues.

**Pull request merged**
