### PR TITLE
add struct(deepcopy/pointer array) syntax checks

### PR DESCRIPTION
**Pull request by yanxue-intel**
Signed-off-by: yan xue <yan.xue@intel.com>

### CODE REVIEW

**Comment by yanxue-intel** [comment]
bors try

**Comment by jinghe-INTC** [comment]
bors try

**Comment by yanxue-intel** [comment]
> ## try
> Build failed:
> 
> * [continuous-integration/jenkins/branch](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/job/Bors/job/trying/1039/display/redirect)

I can't see the details of failure in the link above.

**Comment by jinghe-INTC** [comment]
bors try

**Comment by yanxue-intel** [comment]
CI/CD seems not stable and get  many "timeout" error.  @anakrish @mingweishih Please help to check this problem, Thanks.

**Comment by BRMcLaren** [comment]
bora try

**Comment by BRMcLaren** [comment]
bors try

**Comment by yanxue-intel** [comment]
@anakrish please help to merge this PR, thanks.

**Comment by anakrish** [comment]
bors try

**Review by anakrish — APPROVED** [review]
LGTM

**Review by mingweishih — APPROVED** [review]

**Comment by anakrish** [comment]
@manojrupireddy Can you enable the commented out tests in this PR once you have implemented the appropriate validations in oeedger8r

**Pull request merged**
