### PR TITLE
Make VS extension work for Linux simulation mode

### LINKED ISSUE #3691: Update VS extension support matrix documentation
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/visualstudio_dev.md says:

- The following matrix shows what combinations are supported in this version:
```
- OS       Platform           Mode         Supported?
- -------  ----------------   -----------  ----------
- Windows  Intel non-SGX      Simulation   Not yet
- Windows  SGX1               any          Yes
- Windows  SGX1+FLC           any          Yes
- Windows  OP-TEE/TrustZone   any          Not yet
- Linux    Intel non-SGX      Simulation   <needs testing>
- Linux    SGX1               any          <needs testing>
- Linux    SGX1+FLC           any          <needs testing>
- Linux    OP-TEE/TrustZone   any          <needs testing>
```

The Windows non-SGX Simulation now works, so that line should say Yes.
The Linux lines should say "Not yet" per issue #3690

### PR DESCRIPTION
**Pull request by dthaler**
Only verified with simulation mode (using a Linux VM)
so listed others as "in progress" since they need more testing

Fixes #3691 
Also addresses part of #3690 

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Comment by HernanGatta** [comment]
I ran through the [Linux development instructions](https://github.com/openenclave/openenclave/blob/beb532715f70ccffc27c694a89ee3f6319922cd3/docs/GettingStartedDocs/VisualStudioLinux.md). `oeedger8r` doesn't seem to ever run and the `*_u.*` and `*_t.*` files are not generated. I don't think that this changeset is responsible though.

To test this, I cloned `dthaler:vslinux`, opened the VS extension solution with VS 2019, and built it. It created an Ubuntu 18.04 VM and installed the SDK as indicated by the guide in the link above. I then wired VS into the VM both in the settings as well as in both projects (host and enclave), as requested in the guide. I can see activity in the VM when I build, so VS is connected to it.

This was done on clean environments: I installed Windows 10 20H2 and VS Community 2019 (C++ development, Linux development, VS extension development) and I installed Ubuntu 18.04 both from scratch.

Ideas?

**Comment by dthaler** [comment]
bors try

**Comment by radhikaj** [comment]
@dthaler , can you please resolve conflicts?

**Comment by radhikaj** [comment]
@mingweishih , please review.

**Review by radhikaj — APPROVED** [review]

**Comment by radhikaj** [comment]
bors try

**Pull request merged**
