### PR TITLE
Changelog message for malloc info API.

### PR DESCRIPTION
**Pull request by achamayou**
Add entry in the changelog for malloc info API.

### CODE REVIEW

**Comment by achamayou** [comment]
bors try

**Review by radhikaj — APPROVED** [review]
Thanks for the addition
It looks like there is a merge commit, can you look into that?

**Comment by achamayou** [comment]
@radhikaj sorry, yes, it's because I used the web editor I think. Fixed now.

**Review by dthaler — APPROVED** [review]

**Pull request merged**
