### PR TITLE
Fix pip3 and clang-11/10 support

### PR DESCRIPTION
**Pull request by CyanDevs**
* Upgrade pip3 as we use that and some Ubuntu 18.04 images do not have pip installed/symlinked
* Explicitly include clang-10 when finding clang version
* Script for installing lvi mitigation bindir will now install clang-11

### CODE REVIEW

**Comment by anakrish** [comment]
Is there some way to assert that tests are being using the expected compiler (e.g: clang-11)?

**Comment by CyanDevs** [comment]
I will have to explore that, and if you don't mind, it should be done after this PR as this doesn't affect which clang version is used during build/test -- it will however add lvi mitigation binary for clang-11 (and not create one for clang-8/9 if present).

**Review by radhikaj — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]

**Comment by CyanDevs** [comment]
Windows agent disconnect -- retrying now to skip waiting another 30 min for the timeout.

**Pull request merged**
