### PR TITLE
Change NuGet package description to use NuGetDescription.txt. Fix #2496

### LINKED ISSUE #2496: A nuget package's Description property may not be more than 4000 characters long.
The OE current description is too long and is causing issues with releases when uploading Nuget Packages.

Currently, the description is 4005 characters long. When packaged, it becomes 4036, as it stands our packaging description comes from the README. When viewed in plain text, this could be improved by providing a description.md that we build from to keep the attention focused on what the product accomplishes.

### PR DESCRIPTION
**Pull request by radhikaj**
The NuGet package currently use https://github.com/openenclave/openenclave/README.md for the description property. This is problematic because it is too long. See #2496. Change settings so NuGetDescription.txt is used instead.

Signed-off-by: Radhika Jandhyala <radhikaj@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
Thanks @BRMcLaren and @CodeMonkeyLeet for revieweing.

**Pull request merged**
