### PR TITLE
Support exception handler stack registration per exception type in SGX

### PR DESCRIPTION
**Pull request by mingweishih**
This PR allows the enclave to register the exception handler for the exception types supported by the SGX hardware.
Note
- If setting the exception handler stack, the stack will be used by the first-stage handler regardless registering the stack or not.
- If not registering the stack for a exception type, the second-stage handler for that exception type fallback to use the default stack.

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Review by anakrish — APPROVED** [review]

**Review by CyanDevs — APPROVED** [review]

**Pull request merged**
