### PR TITLE
Update OpenSSL to v1.1.1h

### PR DESCRIPTION
**Pull request by CyanDevs**
Signed-off-by: Chris Yan <22492275+CyanDevs@users.noreply.github.com>

### CODE REVIEW

**Comment by CyanDevs** [comment]
Started E2E here: https://oe-jenkins-tf.westeurope.cloudapp.azure.com/job/CI-CD_Infrastructure/job/OpenEnclave-E2E-Testing/253/console

**Review by BRMcLaren — APPROVED** [review]

**Review by rs-- — APPROVED** [review]

**Pull request merged**
