### PR TITLE
Update licensing

### PR DESCRIPTION
**Pull request by anju2408**

### CODE REVIEW

**Review by radhikaj — APPROVED** [review]
Thanks!

**Comment by mingweishih** [comment]
Can you sign-off the commit? Thanks

**Review by dthaler — APPROVED** [review]

**Comment by radhikaj** [comment]
> Can you sign-off the commit? Thanks

@anju2408 , you can do this via git commit --amend -s, followed by a gitpush.

**Comment by radhikaj** [comment]
Thanks for the PR @anju2408. I am closing this PR since it needs DCO sign off to be merged. Please reopen when you are able to sign off.

**Pull request closed without merging**
