### PR TITLE
Enable libcxxrt test on Windows

### LINKED ISSUE #1034: Support libunwind and libc tests for ELF enclaves on Windows
The following tests relating to libc/libunwind are currently disabled on Windows because their functionality was not appropriately supported before. 
- backtrace
- libunwind
- stdc 

The causes for their failures on a Windows host need to be investigated; in particular, issues with libunwind/backtrace suggest issues that need to be fixed for the story around parity with Linux behaviors (#376)

Also need to investigate enabling the libcxx related tests on Windows:
- libcxx
- libcxxrt

### PR DESCRIPTION
**Pull request by mingweishih**
This PR enables libcxxrt test on Windows.

Fixes #1034.

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Comment by radhikaj** [comment]
Great work, @mingweishih .

**Pull request merged**
