### PR TITLE
change packaging with ninja to cpack

### PR DESCRIPTION
**Pull request by BRMcLaren**
Signed-off-by: brmclare <brmclare@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Review by rs-- — APPROVED** [review]
Fixes #3271

**Comment by radhikaj** [comment]
Do current Jenkins jobs on Windows do this as the last step?

**Comment by BRMcLaren** [comment]
> Do current Jenkins jobs on Windows do this as the last step?

The documentation and our release process using Ninja (regular package not host verify)

https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsInstallInfo.md#create-a-redistributable-sdk-package

**Review by mingweishih — APPROVED** [review]

**Pull request merged**
