### PR TITLE
oe_malloc/oe_free for oe_cert_verify and asym_keys

### LINKED ISSUE #3438: malloc/free used in two places while oe_malloc/oe_free as used elsewhere
Binary analysis of echo_enc reveals that malloc/free is used by [`oe_cert_verify`](https://github.com/openenclave/openenclave/blob/baa31bc8ff8164611f07c9162085a3f1e5362ade/enclave/crypto/cert.c#L851) and [`_export_keypair`](https://github.com/openenclave/openenclave/blob/816e0be5b47f7da600d85cc7857756800dbacc8e/enclave/asym_keys.c#L202) functions.

We can see that rest of the OE SDK mainly uses `oe_malloc` and `oe_free`.

Are these uses of malloc/free intended?

```
 malloc 0x62230
  ├── _export_keypair 0x5a2b0
  │   └── _derive_asymmetric_key 0x58f50
  │       ├── _load_asymmetric_key_by_policy 0x567d0
  │       │   └── oe_get_public_key_by_policy 0x56750
  │       │       └── oe_get_public_key_by_policy_ecall 0x57bc0
  │       └── _load_asymmetric_key 0x57330
  │           └── oe_get_public_key 0x572b0
  │               └── oe_get_public_key_ecall 0x58410
  └── oe_cert_verify 0x73b40
      └── oe_validate_revocation_list 0x24430
          └── oe_get_sgx_quote_validity 0x1e0a0
              ├── oe_verify_quote_with_sgx_endorsements 0x1a360
              │   ├── oe_verify_sgx_quote 0x197a0
              │   │   └── oe_verify_report_internal 0x13590
              │   │       ├── oe_verify_report_ecall 0x14800
              │   │       ├── _verify_report 0x4d440
              │   │       └── _verify_local_report 0x4dae0
              │   │           └── _verify_evidence 0x4b7e0
              │   └── _verify_evidence 0x4b7e0
              └── _fill_with_known_claims 0x47450
                  └── oe_sgx_extract_claims 0x45920
                      └── _verify_evidence 0x4b7e0
```

### PR DESCRIPTION
**Pull request by qiucwang**
Fixes #3438 

Signed-off-by: Qiucheng Wang <qiucwang@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
@qiucwang Thanks for cleaning up the use of malloc/free.
I got fetched your branch, built echo_enc and ran the analysis again.
There are no longer any use of `malloc`.
Can you take a look at enclave/sgx/collateralinfo.c? It seems to use realloc, calloc and free functions.

```
 realloc 0x62560 /home/anakrish/work/pr/include/openenclave/corelibc/bits/malloc.h:26
  └── oe_get_sgx_quote_verification_collateral 0x51e80 /home/anakrish/work/pr/enclave/sgx/collateralinfo.c:149 ...
```

```
 free 0x624c0 /home/anakrish/work/pr/include/openenclave/corelibc/bits/malloc.h:14
  ├── oe_free_sgx_quote_verification_collateral_args 0x53ab0 /home/anakrish/work/pr/enclave/sgx/collateralinfo.c:458 ...
```

**Comment by qiucwang** [comment]
> @qiucwang Thanks for cleaning up the use of malloc/free.
> I got fetched your branch, built echo_enc and ran the analysis again.
> There are no longer any use of `malloc`.
> Can you take a look at enclave/sgx/collateralinfo.c? It seems to use realloc, calloc and free functions.
> 
> ```
>  realloc 0x62560 /home/anakrish/work/pr/include/openenclave/corelibc/bits/malloc.h:26
>   └── oe_get_sgx_quote_verification_collateral 0x51e80 /home/anakrish/work/pr/enclave/sgx/collateralinfo.c:149 ...
> ```
> 
> ```
>  free 0x624c0 /home/anakrish/work/pr/include/openenclave/corelibc/bits/malloc.h:14
>   ├── oe_free_sgx_quote_verification_collateral_args 0x53ab0 /home/anakrish/work/pr/enclave/sgx/collateralinfo.c:458 ...
> ```

**Comment by qiucwang** [comment]
> @qiucwang Thanks for cleaning up the use of malloc/free.
> I got fetched your branch, built echo_enc and ran the analysis again.
> There are no longer any use of `malloc`.
> Can you take a look at enclave/sgx/collateralinfo.c? It seems to use realloc, calloc and free functions.
> 
> ```
>  realloc 0x62560 /home/anakrish/work/pr/include/openenclave/corelibc/bits/malloc.h:26
>   └── oe_get_sgx_quote_verification_collateral 0x51e80 /home/anakrish/work/pr/enclave/sgx/collateralinfo.c:149 ...
> ```
> 
> ```
>  free 0x624c0 /home/anakrish/work/pr/include/openenclave/corelibc/bits/malloc.h:14
>   ├── oe_free_sgx_quote_verification_collateral_args 0x53ab0 /home/anakrish/work/pr/enclave/sgx/collateralinfo.c:458 ...
> ```

Sure. I'll take a look.

**Pull request merged**
