### PR TITLE
create enclaves from multiple child and parent processes

### PR DESCRIPTION
**Pull request by jinghe-INTC**
It is a enhancement of the case of creating enclave in child process.

### CODE REVIEW

**Comment by jinghe-INTC** [comment]
bors try

**Comment by jinghe-INTC** [comment]
> LGTM
> Thanks for locking down various fork scenarios.

No problem.
Unfortunately it didn't pass the code coverage check: "Coverage of 59.60% is lower than expected 60.00%." I am thinking about how to fix it.

**Comment by mingweishih** [comment]
> > LGTM
> > Thanks for locking down various fork scenarios.
> 
> No problem.
> Unfortunately it didn't pass the code coverage check: "Coverage of 59.60% is lower than expected 60.00%." I am thinking about how to fix it.

You can ignore that for now. We currently didn't take the code coverage as hard requirement. It's more like an experimental feature.

**Pull request merged**
