### PR TITLE
Update to Intel PSW 2.10.100.2

### PR DESCRIPTION
**Pull request by CyanDevs**
Updates to the PSW v2.10.100.2 for Windows

DCAP version remains at v1.8.100.2

Signed-off-by: Chris Yan <chrisyan@microsoft.com>

### CODE REVIEW

**Review by mingweishih — APPROVED** [review]
LGTM

**Review by radhikaj — APPROVED** [review]
Thanks @CyanDevs !

**Comment by CyanDevs** [comment]
Builds were failing before this PR due to a file validation issue, which is now fixed in #3657 and merged to master. So this tested again and it should work.

**Review by achamayou — APPROVED** [review]

**Pull request merged**
