### PR TITLE
Fix scripts/install-windows-prereqs.ps1 script

### PR DESCRIPTION
**Pull request by ionutbalutoiu**
* Fix scripts/install-windows-prereqs.ps1
  * Append the OpenSSL bin directory to the system PATH via the
    `-EnvironmentPath` parameter from the `Install-Tool` function.
    The logic behind `-EnvironmentPath` parameter makes sure that
    the PATH is not updated twice if the directory is already
    appended.
  * Remove redundant extra logic, from the `Install-OpenSSL`
    function, to append bin directory to system PATH. This also
    caused OpenSSL bin directory to be appended to the system PATH
    on every script execution. Therefore, it broke the idempotency
    of the entire script.
* Add missing error check for `.\InstallAzureDCAP.ps1`

Signed-off-by: Ionut Balutoiu ibalutoiu@cloudbasesolutions.com

### CODE REVIEW

**Comment by ionutbalutoiu** [comment]
While fixing the `install-windows-prereqs.ps1` script, I discovered that we are impacted by the following issues with the `InstallAzureDCAP.ps1`  script: https://github.com/microsoft/Azure-DCAP-Client/issues/95.

I already opened a PR to fix the `InstallAzure-DCAP.ps1` script: https://github.com/microsoft/Azure-DCAP-Client/pull/96.

**Comment by kuanggang-git** [comment]
Can one of the admins verify this patch?

**Comment by jhand2** [comment]
Failure due to failed docker login. Trying again

bors r+

**Comment by jhand2** [comment]
Samples timed out on windows. Opening an issue for this and trying again

bors r+

**Pull request merged**
