### PR TITLE
Brmclare/psw dcap upgrade

### PR DESCRIPTION
**Pull request by BRMcLaren**
This PR updates the cache, docs and scripts to the latest PSW/DCAP versions

### CODE REVIEW

**Comment by BRMcLaren** [comment]
@ryanhsu19  E2E is running here: https://oe-jenkins-tf.westeurope.cloudapp.azure.com/job/CI-CD_Infrastructure/job/OpenEnclave-Rebuild-Infrastructure/260/ and waiting on completion.

**Comment by BRMcLaren** [comment]
Failed for unrelated reason: https://oe-jenkins-tf.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/287/pipeline.

@rs--  @radhikaj  @ryanhsu19  mind giving this a once over when you get a moment?

**Review by rs-- — APPROVED** [review]
lgtm

**Review by radhikaj — APPROVED** [review]
Thanks so much @BRMcLaren.

**Pull request merged**
