### PR TITLE
Split pipeline Jenkinsfiles

### PR DESCRIPTION
**Pull request by oprinmarius**
Removed unused Jenkinsfiles , deployment templates and scripts
Merged nightly_build.Jenkinsfile with Jenkinsfile and added a parameter to switch between FULL TEST SUITE and the faster PR testing

Split our current Jenkins pipeline in multiple Jenkinsfiles
Azure/Windows
Azure/Linux
Agnostic/Linux

Moved nightly jobs to Azure/Nightly folder

Allow the use of custom shared library

### CODE REVIEW

**Comment by oprinmarius** [comment]
!bors try

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try-

**Comment by BRMcLaren** [comment]
The SDK has a badge currently for different build types, nightly libcxx etc. When this gets merged, it will break the nightly build badge. 

We should either remove the badge from the READ.me or swap out the badges when ready to split them up..

**Comment by BRMcLaren** [comment]
@oprinmarius @ionutbalutoiu, I think an idea to get this merged up without breaking anything is to add badges.

Could you create pipelines on to call these Jenkins files and add badges to the Read.me with references to these pipelines? This would allow us to categorize and show what is currently up and help to validate this work. It would require us to leave the JenkinsFile in to allow Bors to merge in. 

This would solve the chicken and egg problem with multi-status checks.

Thoughts?

**Comment by kuanggang-git** [comment]
Can one of the admins verify this patch?

**Comment by BRMcLaren** [comment]
This looks great!

**Comment by ionutbalutoiu** [comment]
bors try

**Comment by ionutbalutoiu** [comment]
bors try

**Comment by ionutbalutoiu** [comment]
bors try

**Comment by ionutbalutoiu** [comment]
bors try

**Comment by ionutbalutoiu** [comment]
Increased the Windows `ctest` tests timeout from 8 minutes to 20 minutes to see if we still have failures.

bors try

**Comment by BRMcLaren** [comment]
Bors r+

**Comment by BRMcLaren** [comment]
Bors r-

**Pull request merged**
