### PR TITLE
Upgrade snmalloc to v0.4.0

### PR DESCRIPTION
**Pull request by achamayou**
This is primarily to pick up the fix for #2802, but v0.4.0 contains a number of other improvements as well: https://github.com/microsoft/snmalloc/releases/tag/v0.4.0

Checked builds passed with gcc-8, gcc-9, clang-7, clang-8, clang-9

### CODE REVIEW

**Comment by achamayou** [comment]
bors try

**Comment by anakrish** [comment]
@achamayou 
Thanks for fix the issue. We are getting very close to having snmalloc as a potential choice for default allocator.

There is just one more issue that was mentioned in comments in #2292 
snmalloc seems to be compiled using system-headers instead of oe library headers.
Can you see if that can be fixed too? Or would you rather that be addressed in a separate PR?

**Comment by achamayou** [comment]
@anakrish ah I’d missed that, I’ll take a look tomorrow, it should be easy enough to fix.

**Comment by achamayou** [comment]
@anakrish I think that's best done separately, because:

1. It isn't all that clear where the right place to get those includes is without adding a dependency I don't think we want. I've come up with this, but a review from someone who's more familiar with the build would be very helpful:

```
    set_source_files_properties(sgx/snmalloc/snmalloc_wrapper.cpp PROPERTIES COMPILE_FLAGS
        "-std=c++17 -mcx16 -fno-exceptions -nostdinc -nostdinc++ -I../3rdparty/libcxx/libcxx/include -Ioutput/include/openenclave/libc -I../include/openenclave/internal")
```

2. snmalloc's aal_x86.h includes some things that are missing from OE's libcxx headers, such as cpuid.h and emmintrin.h. They aren't used when snmalloc is configured to be used from OPEN_ENCLAVE, but the includes still happen, so I need to fix that.

So for now I suggest merging this to fix the gcc build at least, and sorting out the includes in a separate PR. Your input on 1. would be welcome for that.

**Comment by achamayou** [comment]
@mikbras @CodeMonkeyLeet could you review please? The bors message is somewhat cryptic, but I guess it means at least one code owner should review?

**Pull request merged**
