### PR TITLE
Remove the use of deprecated cmake functions on Windows build for Mbed TLS

### PR DESCRIPTION
**Pull request by mingweishih**
The PR cleans up the CMakeLists.txt for the Mbed TLS build. The changes include:
- Remove the use of `toolchain-clangw.make`, which uses deprecated cmake functions (`CMAKE_FORCE_C_COMPILER`, CMAKE_FORCE_CXX_COMPILER). This file is no longer needed given the current `maybe_build_using_clangw` and `clangw` implementation.

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

**Review by anakrish — APPROVED** [review]

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Review by radhikaj — APPROVED** [review]
Bors r+

**Pull request merged**
