### PR TITLE
add nested switchless calls, call ecall->ocall->ecall->ocall

### PR DESCRIPTION
**Pull request by yanxue-intel**
Signed-off-by: yan xue <yan.xue@intel.com>

### CODE REVIEW

**Comment by jinghe-INTC** [comment]
bors try

**Comment by jhand2** [comment]
@anakrish is this expected to work?

**Comment by anakrish** [comment]
> @anakrish is this expected to work?

For switchless calls it should work. For normal calls it won't work since re-entrant ecalls are not supported.

@yanxue-intel  This is a great test!

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
I couldn't get this test to fail, even after running it in a loop for 1000 times.

**Comment by anakrish** [comment]
I am able to reproduce this with debug builds. USE_DEBUG_MALLOC is turned on only in debug builds.

**Comment by anakrish** [comment]
This test and the associated failure due to memory leaks has revealed a long standing bug with switchless manager cleanup: enclave was being destructed before the switchless manager was cleaned up. This resulted in memory being reported as leaks.

Provided a fix in #2927

**Comment by anakrish** [comment]
bors try

**Pull request merged**
