### PR TITLE
Add support for pthread_spin_trylock()

### LINKED ISSUE #3483: Why is pthread_spin_trylock() not provided?
Open Enclave provides partial support for standard POSIX/LibC functions. The current support is listed [here](https://github.com/openenclave/openenclave/blob/master/docs/LibcSupport.md). This list does not include `pthread_spin_trylock()`. All other `pthread_spin_` functions _are_ supported, as far as I can tell only `trylock` is missing

Why is this? Is there a technical reason why `trylock` is not supportable? Or is this an accidental omission?

From a quick read of the code it looks like the `oe_spin_lock` implementation could be `oe_spin_trylock` with only slight modification, and this could be wrapped/exposed as `pthread_spin_trylock` in the same manner as the other `pthread_spin_` functions.

### PR DESCRIPTION
**Pull request by larrywxyz**
Closes #3483

### CODE REVIEW

**Review by CodeMonkeyLeet — COMMENTED** [review]
Thanks for addressing this gap! Can you also please add a test for this method to tests/thread?

**Review by achamayou — APPROVED** [review]

**Comment by achamayou** [comment]
bors try

**Review by CodeMonkeyLeet — APPROVED** [review]

**Comment by achamayou** [comment]
Azure Linux failed with a timeout on tests/create-rapid:

image

The Windows build hit this:

image

which looks like #3530.

Neither of those is obviously related to the change, so running the CI again.

**Pull request merged**
