### PR TITLE
[Mystikos] oelldb: Delay handling module notifications until after EINIT

### PR DESCRIPTION
**Pull request by anakrish**
Mystikos currently notifies the debugger about regions (modules)
before the enclave has been EINITED.

When the debugger tries to set any pending breakpoints in the
just added module, it fails since SGX hardware prevents the
debugger from modifying contents of pages within the region.
The pages have been measured; but the EINIT has not yet been
performed.
GDB seems to retry setting the breakpoint in the region once
the enclave has been registered which happens after EINIT.
lldb seems to give up after the first failure setting the
breakpoint. Therefore, pending breakpoints in myst kernel module
work with GDB whereas they don't work with LLDB.

The fix in this PR delays registering the module until after
the enclave itself has been registered. The module is
added to a list which is processed in the handler for enclave
creation.

fixes: https://github.com/deislabs/mystikos/issues/557

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Review by jxyang — APPROVED** [review]

**Comment by jxyang** [comment]
There are failures on the Mystikos pipeline. Please refrain from merging now.

**Comment by anakrish** [comment]
@jxyang Are the failures related to this PR? If so, do let me know so that I can investigate.

**Comment by jxyang** [comment]
https://openenclave.visualstudio.com/ACC-Services/_build/results?buildId=9754&view=logs&j=ab477ad6-9781-5b54-82ca-a0141b26726e

**Comment by anakrish** [comment]
Ok. Then it is most likely related.
Can you give me access to the pipeline? I cannot seem to open it.

**Comment by vtikoo** [comment]
@anakrish tests/dotnet-sos is failing for linux target.

**Review by radhikaj — APPROVED** [review]
bors r+

**Comment by mingweishih** [comment]
This PR is for Mystikos OE branch. I think we're still waiting for the validation on the Mystikos side.

**Comment by vtikoo** [comment]
PR is passing dotnet-sos tests now - https://openenclave.visualstudio.com/ACC-Services/_build/results?buildId=10161&view=logs&j=ab477ad6-9781-5b54-82ca-a0141b26726e.

**Review by vtikoo — APPROVED** [review]

**Comment by anakrish** [comment]
Merging.

**Pull request merged**
