### PR TITLE
reopen test case child_process_destroy

### PR DESCRIPTION
**Pull request by jinghe-INTC**
update case by adding one second's sleep

update comment

Signed-off-by: Jing He <jing.j.he@intel.com>

### CODE REVIEW

**Comment by jinghe-INTC** [comment]
bors try

**Comment by jinghe-INTC** [comment]
bors try

**Comment by anakrish** [comment]
@jinghe-INTC Does adding 1 second sleep fix #3099 ?

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Comment by jinghe-INTC** [comment]
> @jinghe-INTC Does adding 1 second sleep fix #3099 ?

Yes. It looks working around the unstable issue. I will try to root cause it.

**Comment by jinghe-INTC** [comment]
It does not have to be a sleeping before the destroying in the child process, some extra printing like "printf("%d\n", __LINE__);" will also make it stable. However, if the printing is after the destroying, the case is unstable like before.

**Comment by mingweishih** [comment]
> It does not have to be a sleeping before the destroying in the child process, some extra printing like "printf("%d\n", **LINE**);" will also make it stable. However, if the printing is after the destroying, the case is unstable like before.

Does it also imply that making any ocall before termination should work?
Also, instead of sleep, can you do some dummy operations (without making any ocall) and see if that work? Thanks!

**Comment by jinghe-INTC** [comment]
> > It does not have to be a sleeping before the destroying in the child process, some extra printing like "printf("%d\n", **LINE**);" will also make it stable. However, if the printing is after the destroying, the case is unstable like before.
> 
> Does it also imply that making any ocall before termination should work?
> Also, instead of sleep, can you do some dummy operations (without making any ocall) and see if that work? Thanks!

1. I tried to copy the same ecall from parent process before termination and it didn't make any difference, still unstable.
2. A printing of PID of child process before termination made it more stable, although there is still about 1~2% occurrences of segmentation fault.
3. A sleep(0) also made it more stable, although there is still about 1~2% occurrences of segmentation fault. Is it one of the dummy operations you meant?

**Comment by mingweishih** [comment]
> > > It does not have to be a sleeping before the destroying in the child process, some extra printing like "printf("%d\n", **LINE**);" will also make it stable. However, if the printing is after the destroying, the case is unstable like before.
> > 
> > 
> > Does it also imply that making any ocall before termination should work?
> > Also, instead of sleep, can you do some dummy operations (without making any ocall) and see if that work? Thanks!
> 
> 1. I tried to copy the same ecall from parent process before termination and it didn't make any difference, still unstable.
> 2. A printing of PID of child process before termination made it more stable, although there is still about 1~2% occurrences of segmentation fault.
> 3. A sleep(0) also made it more stable, although there is still about 1~2% occurrences of segmentation fault. Is it one of the dummy operations you meant?

Ah, I thought the operations were inside the enclave.

**Pull request merged**
