### PR TITLE
Add build option to OE to disable building of tests

### LINKED ISSUE #2894: Add BUILD_TESTS as CMake build option
It would be nice if one could disable building of the tests.

### PR DESCRIPTION
**Pull request by jhand2**
Add build option to OE to disable building of tests

Fixes #2894

### CODE REVIEW

**Comment by radhikaj** [comment]
Thanks a lot for taking this on @jhand2. to build tests, you have to opt in? Can the opt-in be to exclude tests?

**Comment by jhand2** [comment]
> Thanks a lot for taking this on @jhand2. to build tests, you have to opt in? Can the opt-in be to exclude tests?

I set he default to `ON`. So if you don't pass any option to cmake, it will build the tests by default

**Pull request merged**
