### PR TITLE
Update VS extension to OE 0.11

### PR DESCRIPTION
**Pull request by dthaler**
Changes:
* Add System EDLs (syscall.edl and platform.edl).  PR #2961 did this for samples but not for the VS extension
* Remove dependencies on sgx_enclave_common.lib and sgx_dcap_ql.lib.  (Anand, please let me know if this is incorrect.)
* Add dependency on shlwapi.lib since oehost.lib now depends on it for PathCombineW
* Update package dependencies to latest versions to pick up any bug fixes
* Update version numbers of OE and the extension

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Review by anakrish — APPROVED** [review]
LGTM.

Does the extension framework allow specifying the oe version in a single place and referring to it everywhere else?

**Comment by dthaler** [comment]
> LGTM.
> 
> Does the extension framework allow specifying the oe version in a single place and referring to it everywhere else?

Unfortunately no.  That's why I use a command to find and replace all instances (see step 3 at a [PR I am working on](https://github.com/dthaler/openenclave/blob/vsext-release-doc/devex/vsextension/vsix-release-process.md) to document what steps are done now... this needs to be improved in the future but the first step is just to document what we do now for the VS extension).

**Review by mingweishih — APPROVED** [review]

**Pull request merged**
