### PR TITLE
CI/CD build Optimization

### PR DESCRIPTION
**Pull request by mingweishih**
The PR optimizes the CI/CD build by reducing the number of configurations specified in the Jenkinsfile.
Also, create a copy of the original Jenkinsfile as nightly_build.Jenkinsfile (plus minor modification to enable full tests with LVI mitigation), which we should consider run as the nighly build.

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
@mingweishih would you be so kind as to do the same changes outline here?

https://github.com/openenclave/openenclave/pull/2754

We are going to end up in a merge conflict otherwise as we are splitting the Jenkins files.

**Comment by radhikaj** [comment]
> @mingweishih would you be so kind as to do the same changes outline here?
> 
> #2754
> 
> We are going to end up in a merge conflict otherwise as we are splitting the Jenkins files.

@BRMcLaren Can we get this change in and then resolve conflicts on the other please?

**Pull request merged**
