### PR TITLE
Log abort backtrace with log level error

### PR DESCRIPTION
**Pull request by anakrish**
Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Review by mingweishih — APPROVED** [review]

**Review by mingweishih — COMMENTED** [review]
Need to see if the sgx/backtrace test needs to be updated as now we will always have two backtrace printed when SIGSEGV occurs.

**Comment by anakrish** [comment]
CI node access failure in Windows.

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
> Need to see if the sgx/backtrace test needs to be updated as now we will always have two backtrace printed when SIGSEGV occurs.

The test passes fine. Do you anticipate any problems?

**Comment by mingweishih** [comment]
> > Need to see if the sgx/backtrace test needs to be updated as now we will always have two backtrace printed when SIGSEGV occurs.
> 
> The test passes fine. Do you anticipate any problems?

No, as long as the pipeline passes :)

**Comment by anakrish** [comment]
bors try

**Review by radhikaj — APPROVED** [review]

**Comment by anakrish** [comment]
code format error

**Comment by anakrish** [comment]
bors try

**Pull request merged**
