### PR TITLE
Enable printf-style format checks for oe_log()

### PR DESCRIPTION
**Pull request by mikbras**
This PR enables printf-style format checking for oe_log() as shown.

```c++
OE_PRINTF_FORMAT(2, 3)
oe_result_t oe_log(oe_log_level_t level, const char* fmt, ...);
```

It also fixes all the places that incompatible format specifiers were used (for example: passing **size_t** to **%d**).

I also fixed **OE_RAISE_MSG()** to work around the **__VA_ARGS__** comma limitation on Windows.

### CODE REVIEW

**Comment by mikbras** [comment]
bors try

**Comment by mikbras** [comment]
bors try

**Comment by mikbras** [comment]
bors try

**Comment by jhand2** [comment]
Looks good. Please squash commits and add DCO for merging.

**Comment by mikbras** [comment]
Closing because merge process failed. Will create new PR on fresh master.

**Pull request closed without merging**
