### PR TITLE
Add tests after 3rdparty modules.

### PR DESCRIPTION
**Pull request by anakrish**
This ensures that 3rdparty contents are fetched before
tests are configured.

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Review by mingweishih — APPROVED** [review]

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try-

**Comment by anakrish** [comment]
Ordering has already been fixed as part of OE apkman PR:
https://github.com/openenclave/openenclave/blob/1e66298a4328d1ed7e8fa3d619f4f2c1616bf39d/CMakeLists.txt#L421-L432

**Pull request closed without merging**
