### PR TITLE
Implement PEEK_USER and POKE_USER

### PR DESCRIPTION
**Pull request by anakrish**
These ptrace calls are used by lldb to fetch GPRs.

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Review by mingweishih — APPROVED** [review]
LGTM

**Comment by BRMcLaren** [comment]
LGTM

**Review by BRMcLaren — APPROVED** [review]

**Pull request merged**
