### PR TITLE
Add Windows support for getnameinfo and getaddrinfo

### PR DESCRIPTION
**Pull request by dthaler**
getaddrinfo was partially supported already but did not correctly handle non-ASCII hostnames
(for background on Windows Unicode support, see the description of PR #2809).

Also fixes some bugs in the resolver test which previously assumed a machine was IPv4 only and so would fail on any machine that was IPv6-enabled, and also assumed that the oe_addrinfo layout in the OE EDL file matched the native addrinfo layout on the host OS and so would fail on any OS where they didn't exactly match.

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Comment by dthaler** [comment]
bors try

**Comment by dthaler** [comment]
bors try

**Comment by kuanggang-git** [comment]
Can one of the admins verify this patch?

**Comment by dthaler** [comment]
bors try

**Comment by dthaler** [comment]
@BRMcLaren  Can you tell me why the samples test times out?  It looks like there's some 8-minute timeout (480 sec) somewhere that needs to be increased, but I'm not sure where.

**Comment by dthaler** [comment]
bors retry

**Pull request merged**
