### PR TITLE
Test public headers against C99 standard

### LINKED ISSUE #2376: OE is not C99 compliant
From discussing with @mikbras, OE should compile against C99. Unfortunately, it does not.

In particular, the main thing I haven't been able to overcome is OE_STATIC_ASSERT:

```{C}
#define OE_STATIC_ASSERT(COND)       \
    typedef unsigned char OE_CONCAT( \
        __OE_STATIC_ASSERT, __LINE__)[(COND) ? 1 : -1] OE_UNUSED_ATTRIBUTE
```

It depends on type redefinition (`__OE_STATIC_ASSERT<line_number>` can be defined multiple times). Type redefinition is a C11 feature and using it fails the build when the C standard is set to C99.

We'll need to come up with something else if we want OE to be compilable with C99. If we don't care, we can just set the standard to C11 and document that.

### PR DESCRIPTION
**Pull request by mingweishih**
This PR adds a test that compiles all the public headers (3rd party ones are not included) against C99 standard (using `std=gnu99`). Any violation should cause compile-time errors.

Also, cleaning up code that are unnecessary / inconsistent as follows.
* `host/sgx/enclave.h`
   - `typedef` the `struct _oe_enclave` as `oe_enclave_t` because it's used in the following `GetEnclaveEvent` function.
* `include/openenclave/corelibc/bits/types.h `
   - Remove `intptr_t`, `time_t`, and `suseconds_t`, which are already defined in `openenclave/bits/types.h`
* `include/openenclave/internal/crypto/crl.h`
   - Remove a redundant `typedef`

Fixes #2376 #2486

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Comment by jhand2** [comment]
Fails for arm64: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAgnostic-Linux/detail/Agnostic-Linux/81/pipeline

**Comment by mingweishih** [comment]
> Fails for arm64: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAgnostic-Linux/detail/Agnostic-Linux/81/pipeline

Thanks! Investigating now.

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Pull request merged**
