### PR TITLE
add initial approvers/reviewers for prow integration

### PR DESCRIPTION
**Pull request by BRMcLaren**
This PR adds the CGC as the initial owners/reviewers as part of https://github.com/openenclave/openenclave/issues/3640

### CODE REVIEW

**Review by dthaler — APPROVED** [review]

**Review by anakrish — APPROVED** [review]
LGTM

**Review by CodeMonkeyLeet — APPROVED** [review]
LGTM.

Side question, are there instructions for the existing owners to update and expand the owners?e.g. delegate the rights to additional owners in specific SIGs? (Yen Lee et. al. come to mind.)

**Comment by BRMcLaren** [comment]
@CodeMonkeyLeet  Yup, right here: https://github.com/openenclave-ci/test-infra/blob/master/docs/owners.md#owners

If you would like to see this in action, please take a look at this PR: https://github.com/openenclave/openenclave-curl/pull/15

**Comment by BRMcLaren** [comment]
Failures are due to the CI check, adding OWNERS files to ignore list.

**Pull request merged**
