### PR TITLE
Fix socketpair/CMakeLists.txt and resolver/CMakeLists.txt.

### PR DESCRIPTION
**Pull request by nonpolarity**
A following up pr from #2826 
Change cmake config that only to build if BUILD_ENCLAVES, to avoid unexpected build error while enclaves are cross-compiled.

Signed-off-by: Alvin Chen <alvin@chen.asia>

### CODE REVIEW

**Comment by nonpolarity** [comment]
bors try

**Comment by radhikaj** [comment]
Thanks @nonpolarity

**Pull request merged**
