### PR TITLE
Update handling of empty format settings for SGX ECDSA evidence

### LINKED ISSUE #3742: Attestation sample fails when running with quote-ex library installed
Repro steps
1. Install quote-ex package (sudo apt -y install libsgx-quote-ex)
2. run [attestation sample](https://github.com/openenclave/openenclave/tree/master/samples/attestation)

Result:
Invalid parameter error

```
2020-11-19T02:05:23+0000.432742Z [(H)ERROR] tid(0x7fdb7330ac00) | :OE_INVALID_PARAMETER [/source/host/sgx/sgxquote.c:oe_sgx_qe_get_quote:604]
2020-11-19T02:05:23+0000.432781Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed::OE_INVALID_PARAMETER [/source/enclave/core/sgx/report.c:oe_get_remote_report:305]
2020-11-19T02:05:23+0000.432793Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed::OE_INVALID_PARAMETER [/source/enclave/core/sgx/report.c:_oe_get_report_internal:384]
2020-11-19T02:05:23+0000.432805Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed::OE_INVALID_PARAMETER [/source/enclave/core/sgx/report.c:oe_get_report_v2_internal:457]
2020-11-19T02:05:23+0000.432819Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed:SGX Plugin: Failed to get OE report. OE_INVALID_PARAMETER (oe_result_t=OE_INVALID_PARAMETER) [/source/enclave/sgx/attester.c:_get_evidence:173]
2020-11-19T02:05:23+0000.432829Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed::OE_INVALID_PARAMETER [/source/enclave/attest_plugin.c:oe_get_evidence:116]
```

### PR DESCRIPTION
**Pull request by shnwc**
Fix #3742

### CODE REVIEW

**Comment by shnwc** [comment]
bors try

**Review by ryanhsu19 — APPROVED** [review]
Looks good to me, thanks!

**Comment by shnwc** [comment]
bors try

**Review by yentsanglee — APPROVED** [review]

**Review by qiucwang — APPROVED** [review]

**Comment by shnwc** [comment]
bors try

**Pull request merged**
