### PR TITLE
Brmclare/doc fixes

### PR DESCRIPTION
**Pull request by BRMcLaren**
Just some doc fixes

### CODE REVIEW

**Review by radhikaj — APPROVED** [review]
THanks @BRMcLaren

**Review by dthaler — APPROVED** [review]

**Review by dthaler — COMMENTED** [review]
Aren't the same changes needed in install_host_verify_Ubuntu_16.04.md and install_host_verify_Ubuntu_18.04.md?

**Comment by BRMcLaren** [comment]
> Aren't the same changes needed in install_host_verify_Ubuntu_16.04.md and install_host_verify_Ubuntu_18.04.md?

Added, thanks.

**Comment by radhikaj** [comment]
Thanks for addressing the host-verify packages as well.

**Review by dthaler — APPROVED** [review]
Looks good now, thanks for updating the other two files.

**Pull request merged**
