### PR TITLE
Bump up SymCrypt-OpenSSL and SymCrypt module 1

### PR DESCRIPTION
**Pull request by mingweishih**
This PR updates the SymCrypt-OpenSSL submodule and the module loading support for SymCrypt v101.3.0.
The changes for the latter are as follows:

- Expose `__stack_chk_fail` to the module to support stack canary.
- Remove the logic on relying the existence of "DYNAMIC" symbol, which is stripped in the latest symcrypt binary, to find the offset of the dynamic section. Instead, we update the logic to find the offset from the section table.
- Add the support to handle the `DT_PLTGOT` entry relocation.

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

**Review by radhikaj — APPROVED** [review]

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Comment by radhikaj** [comment]
bors try-

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
bors try-

**Comment by radhikaj** [comment]
bors try

**Comment by CyanDevs** [comment]
bors try

**Comment by mingweishih** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Review by CyanDevs — APPROVED** [review]

**Pull request merged**
