### PR TITLE
Set John Kordich as the Release Manager.

### PR DESCRIPTION
**Pull request by johnkord**
This is the PR to nominate making myself (John Kordich) the release manager. It is based on the newly submitted guidelines for selecting a release manager in #2229

### CODE REVIEW

**Comment by andschwa** [comment]
Added all committers as reviewers (I think this works?)

**Comment by johnkord** [comment]
@andschwa I tried that too up above when I created this PR! Not sure if it worked or not :)

**Comment by BRMcLaren** [comment]
Just here to say, that the adding Commitee as reviewers thing, did not work from the above attempts :) 

I added OpenEnclave/Committee and it seems to work on my end, as it shows it now?

**Comment by andschwa** [comment]
I think it goes away when somebody from that group approves...GitHub is weird.

**Comment by johnkord** [comment]
Thanks everyone!

bors r+

**Pull request merged**
