### PR TITLE
Upgrade libcxx to 10.0.1

### PR DESCRIPTION
**Pull request by anakrish**
Remove source files from openenclave repo.
Instead, download, verify and use sources from
archive published by LLVM project.

Note: New features like filesystem are not enabled in
this PR; only existing functionality is upgraded.
New features can be enabled in future PRs depending upon
the testing effort required.

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try-

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try-

**Comment by anakrish** [comment]
bors try

**Review by mingweishih — APPROVED** [review]

**Comment by anakrish** [comment]
bors try

**Review by radhikaj — APPROVED** [review]
bors r+

**Pull request merged**
