### PR TITLE
Reconfigure the fs test(2)

### LINKED ISSUE #2475: Revise tests/CMakeLists.txt
The current logic in the file is not well-organized, including deprecated variable (`WIN32_SIMULATION`) and duplicated logic. This may confuse developers what tests are enabled in which configuration. We should consider revise the file.

### LINKED ISSUE #2668: fs and hostfs test cases rely on additional cmake tests to remove temporary directory
Currently, both fs and hostfs tests (parts of syscall tests) rely on additional cmake tests to remove the temporary directory.
Take the `tests/syscall/hostfs` for example, currently it does:
```
set(TMP_DIR "${CMAKE_CURRENT_BINARY_DIR}/tmp")

add_test(tests/fs1 cmake -E remove_directory "${TMP_DIR}")

add_enclave_test(tests/fs2
    fs_host
    fs_enc
    "${PROJECT_SOURCE_DIR}"
    "${TMP_DIR}")
```

I suggest to removing such patterns and make the test self-contained.

### PR DESCRIPTION
**Pull request by nonpolarity**
Following up PR of #2839 
To enable unit test of cross-compiled enclave, the OS-specified tests must be configurable at host side.
A host library to remove non-empty directory is introduced, in case this function can be reused by other tests.

Fixes #2668 

Signed-off-by: Alvin Chen <alvin@chen.asia>

### CODE REVIEW

**Comment by nonpolarity** [comment]
bors try

**Comment by nonpolarity** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Comment by nonpolarity** [comment]
bors try

**Pull request merged**
