### PR TITLE
Update to Windows Azure DCAP 1.9.0

### PR DESCRIPTION
**Pull request by CyanDevs**
Signed-off-by: Chris Yan <chrisyan@microsoft.com>

### CODE REVIEW

**Review by radhikaj — APPROVED** [review]

**Comment by mingweishih** [comment]
What's the difference between this and #4013?

**Comment by CyanDevs** [comment]
Ah, good catch! I didn't notice that Yen had done it already. It's good that our PRs match up.

I can say this branch has been tested as I have built the updated CI images with this branch, and have successful tests here: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Windows/detail/Azure-Windows/2809/pipeline and https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Windows/detail/Azure-Windows/2806/pipeline

**Review by mingweishih — APPROVED** [review]

**Comment by mingweishih** [comment]
> Ah, good catch! I didn't notice that Yen had done it already. It's good that our PRs match up.
> 
> I can say this branch has been tested as I have built the updated CI images with this branch, and have successful tests here: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Windows/detail/Azure-Windows/2809/pipeline and https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Windows/detail/Azure-Windows/2806/pipeline

Can you close #4013 once this PR is merged?

**Comment by CyanDevs** [comment]
Yes, thanks Ming Wei!

**Pull request merged**
