### PR TITLE
Update PSW and DCAP links since Intel has changed the locations

### PR DESCRIPTION
**Pull request by radhikaj**
Signed-off-by: Radhika Jandhyala <radhikaj@microsoft.com>

### CODE REVIEW

**Comment by radhikaj** [comment]
> Will this be cherry-picked to 0.9.x and 0.10.x branch as well?

Yes

**Comment by rs--** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors delegate

**Comment by anakrish** [comment]
@radhikaj This change looks odd since in one of the previous PRs we went the other way, changing lower case to upper case.
https://github.com/openenclave/openenclave/commit/4bcad78d7c808e7e31f574e8dd9b28ce411d561c

**Comment by anakrish** [comment]
@radhikaj This change looks odd since in one of the previous PRs we went the other way, changing lower case to upper case.
https://github.com/openenclave/openenclave/commit/4bcad78d7c808e7e31f574e8dd9b28ce411d561c

**Comment by radhikaj** [comment]
> @radhikaj This change looks odd since in one of the previous PRs we went the other way, changing lower case to upper case.
> [4bcad78](https://github.com/openenclave/openenclave/commit/4bcad78d7c808e7e31f574e8dd9b28ce411d561c)

I agree @anakrish , but the old links started failing yesterday and I had to therefore change them to lower case.

**Comment by BRMcLaren** [comment]
@radhikaj I suggest closing this in favor of: https://github.com/openenclave/openenclave/pull/3476/files

Having this go in after would lead to issues.

**Pull request merged**
