### PR TITLE
2 oesign cases: 1. sign w/ empty config 2. sign with config containing neg vals

### PR DESCRIPTION
**Pull request by johnvenn**
obselete pull request 3020, the same commit of 3020.

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

**Comment by johnvenn** [comment]
> Approve again given that I already did in the #3020
> 
> Just side note that instead of creating a new PR, the git issue could have been fixed in the #3020. However, to save time, I'm fine with this case.

yes, just to save time, I created a new PR. Thanks a lot for your comment.

**Comment by BRMcLaren** [comment]
bors try

**Pull request merged**
