### PR TITLE
Update the driver link to the most recent version

### PR DESCRIPTION
**Pull request by Zildj1an**
Update the driver link to the most recent version (1.41)
Signed-off-by: Carlos Bilbao <bilbao@vt.edu>

### CODE REVIEW

**Review by CyanDevs — APPROVED** [review]
With kernel 5.8 or later on Ubuntu 20.04, DCAP driver v1.41 would be the minimum installable version so this is a good change. Thanks for your contribution!

**Review by radhikaj — APPROVED** [review]
bors r+

**Comment by radhikaj** [comment]
@Zildj1an  Please sign off your commit

**Comment by Zildj1an** [comment]
@radhikaj I think it's signed now

**Comment by anakrish** [comment]
@Zildj1an Also squash your commits. Maybe you need to rebase to master.

**Comment by Zildj1an** [comment]
That seems like a lot of work, opened new pull request with everything signed, https://github.com/openenclave/openenclave/pull/4199

**Comment by CyanDevs** [comment]
Closing in favor of #4200

**Pull request closed without merging**
