### PR TITLE
Fix consolefs output when redirected to files.

### PR DESCRIPTION
**Pull request by gupta-ak**
This PR does two things:

1. Fixes the `print` test CMake so that the test actually runs. The test shows that the current master branch fails this test.
2. Fixes consolefs to duplicate the standard file descriptors instead of opening them directly, fixing the issues seen in the `print` test.

### CODE REVIEW

**Comment by yakman2020** [comment]
Does this want to be in 0.6? It looks like it.

Does it satisfy the issue #1834?

**Comment by gupta-ak** [comment]
bors try

**Comment by anitagov** [comment]
Nice job @gupta-ak

**Pull request merged**
