### PR TITLE
Fix Blueocean downstream pipeline links

### LINKED ISSUE #2878: Some jenkins builds don't have links to the build logs for each pipeline
Sometimes when Jenkins runs a trying or staging build in the bors pipeline, it doesn't properly show links to the sub-pipelines that it ran.

This is what I see:

image

This is what I expect to see:

image

Note the "Triggered builds" section which links to the job/logs for that pipeline

### PR DESCRIPTION
**Pull request by oprinmarius**
Wrapp downstream pipeline jobs in a stage block

fixes #2878 
Signed-off-by: Oprin Marius <moprin@cloudbasesolutions.com>

### CODE REVIEW

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try-

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try-

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try

**Comment by jhand2** [comment]
Well the good news is the "Triggered builds" shows up :smile:

**Comment by BRMcLaren** [comment]
bors try

**Comment by BRMcLaren** [comment]
bors try

**Pull request merged**
