### PR TITLE
Increase heap size to work with snmalloc (similar change as tests/std…

### PR DESCRIPTION
**Pull request by anakrish**
…cxx)

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Review by mingweishih — APPROVED** [review]

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Review by radhikaj — APPROVED** [review]
bors r+

**Review by achamayou — COMMENTED** [review]
Sorry I hadn't spotted this one in the PR to upgrade 0.6.0

**Pull request closed without merging**
