### PR TITLE
Test for oelldb

### PR DESCRIPTION
**Pull request by anakrish**
Reuse oegdb test enclaves for oelldb testing.

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
@vtikoo This PR uses python scripting to lockdown oelldb.

**Comment by anakrish** [comment]
bors try

**Review by mingweishih — APPROVED** [review]

**Review by radhikaj — APPROVED** [review]

**Comment by rs--** [comment]
Last bors run failed due to:
1. Docker containers were not updated - updating them now
2. RHEL tests failed - PR deprecating RHEL is in the process of being merged

Will re-run bors after everything is done.

**Comment by anakrish** [comment]
Thanks for investigating this @rs--

**Comment by anakrish** [comment]
strace of oelldb within oeciteam/oetools-20.04 reveals:
```
[pid   257] personality(0xffffffff)     = 0 (PER_LINUX)
[pid   257] personality(PER_LINUX|ADDR_NO_RANDOMIZE) = -1 EPERM (Operation not permitted)
[pid   257] lseek(6, 0, SEEK_CUR)       = -1 ESPIPE (Illegal seek)
[pid   257] fstat(6, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
[pid   257] write(6, "personality set failed: Operatio"..., 47) = 47
[pid   254] <... read resumed>"personality set failed: Operatio"..., 1000) = 47
[pid   257] exit_group(1)               = ?
[p
```

lldb is not able to turn off address randomization within the container.

When the container is run with `--privileged`, then lldb works.
We need to find out if there is a fine-tuned way to enable lldb to work within the container instead of relying on `--privileged`.

**Comment by anakrish** [comment]
The command `settings set target.disable-aslr false` disables turning off ASLR, and avoids relying on the personality syscall.
This could work for us.

**Comment by rs--** [comment]
bors cancel

**Pull request merged**
