### PR TITLE
Use acquire/release pattern for `debug allowed`

### PR DESCRIPTION
**Pull request by anakrish**
Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Review by radhikaj — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
This simple change is likely triggering a compiler bug.

**Comment by anakrish** [comment]
bors try

**Pull request merged**
