### PR TITLE
Update version and changelog for v0.16.0

### PR DESCRIPTION
**Pull request by rs--**

### CODE REVIEW

**Comment by rs--** [comment]
bors try

**Comment by rs--** [comment]
bors try

**Review by mingweishih — APPROVED** [review]
Can you squash the commits?

**Review by CyanDevs — APPROVED** [review]

**Comment by CyanDevs** [comment]
Looks good, just needs a rebase to resolve the conflict, and squashed commits

**Review by dthaler — APPROVED** [review]

**Comment by rs--** [comment]
Cleaning up the commits - will recreate this PR

**Pull request closed without merging**
