### PR TITLE
Update Azure DCAP Client to latest release

### PR DESCRIPTION
**Pull request by deschuma**
Update to Azure DCAP v 1.4.2:
- Disables caching if there are permissions issues with the caching folder
- Attempts a few more environment variables and add a fallback location for the cache directory
- Changes default collateral version to V2 (from V1)

### CODE REVIEW

**Comment by jhand2** [comment]
Thanks for your contribution! Could you update the PR description with a quick summary of the change. For example, is this a new release of Azure DCAP or have we been using an old version? Where has this been tested?

Thanks!

**Comment by BRMcLaren** [comment]
Hey @deschuma !

Thank you for your contribution, I am running an infra rebuild here: https://oe-jenkins-tf.westeurope.cloudapp.azure.com/blue/organizations/jenkins/CI-CD_Infrastructure%2FOpenEnclave-E2E-Testing/detail/OpenEnclave-E2E-Testing/182/

Let's ensure it passes before merging into master to keep the CI stable. To @jhand2's point, if the apt repos for Linux have been updated the above test will pick them up. Wanted to check if it was the case they were released?

**Comment by deschuma** [comment]
Thanks! Answering above: yes the apt repos for Linux have already been updated. 
I've updated the instructions

**Comment by BRMcLaren** [comment]
Hello,

The above infra failed because of [this](https://github.com/openenclave/openenclave/issues/2982).
As it is completely unrelated, pushed through the changes in a different manner.

This was the [prior build](https://oe-jenkins-tf.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Windows/detail/Azure-Windows/36/pipeline/), which failed due to an infra timeout.

I am running: [Windows ](https://oe-jenkins-tf.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Windows/detail/Azure-Windows/37/pipeline) tests again, to be safe but I see no issue with merging.

**Pull request merged**
