### PR TITLE
Add Jenkins package tests

### LINKED ISSUE #2119: Addition of package tests
Currently there are not any packaging tests available in Jenkins. This issue is to track the development and addition of such tests.

### PR DESCRIPTION
**Pull request by BRMcLaren**
Addition of Jenkins packaging tests

Fix #2119

### CODE REVIEW

**Comment by johnkord** [comment]
Thanks @oprinmarius ! Also, I think we should validate at least part of the package too, by running the samples tests!

After the "ninja -v package" line for that function, you could run:
```bash
cp -r /opt/openenclave/share/openenclave/samples ~/
cd ~/samples
source /opt/openenclave/share/openenclave/openenclaverc
find . -maxdepth 1 -type d -not -path "." -exec sh -c "echo Running {}; cd {} && make && make run" \;
```

**Comment by BRMcLaren** [comment]
Great idea John. 

Removing Do Not Merge Label, as we are ready to merge now.

**Comment by BRMcLaren** [comment]
bors +

**Comment by BRMcLaren** [comment]
bors+

**Pull request merged**
