### PR TITLE
add correct package location

### LINKED ISSUE #2623: Windows prereqs script fails with new Azure DCAP NuGet
Three days ago, the Azure DCAP NuGet package was updated to version `1.2.0` from `0.0.3`.

The internal structure of the package no longer matches what the Windows prereqs script expects. Thus, the script fails.

[Line 641](https://github.com/openenclave/openenclave/blob/master/scripts/install-windows-prereqs.ps1#L641) in the script references `Azure.DCAP.Windows\script` to invoke `InstallAzureDCAP.ps1`, but the script is now under `Azure.DCAP.Windows\tools` in the NuGet package.

Curiously, even if the prereqs script specifies version `0.0.3` of the Azure DCAP NuGet package by downloading it first and setting a local package source, `nuget` still fetches `1.2.0`.

Additionally, the installation script inside the package (`InstallAzureDCAP.ps1`) was not updated to reflect the change in the package's directory layout, and thus fails even if the prereqs script is updated.

Said script attempts to copy `dll\dcap_quoteprov.dll` to a user-provided installation path, but the DLL is now under `build\native` in the package.

### PR DESCRIPTION
**Pull request by BRMcLaren**
Fixes #2623

Change the Nuget package feed to use source locally and some redundant code clean up.

### CODE REVIEW

**Comment by BRMcLaren** [comment]
Bors try

**Comment by HernanGatta** [comment]
Trying this out locally.

**Comment by HernanGatta** [comment]
@BRMcLaren: Ran the script as modified on a clean Windows Server 2019 VM, worked fine.

**Comment by BRMcLaren** [comment]
@HernanGatta Oh perfect!

Thanks for checking 2019, I just checked 2016.

**Comment by BRMcLaren** [comment]
bors try

**Comment by radhikaj** [comment]
Thanks @brmclaren

**Comment by BRMcLaren** [comment]
bors merge

**Pull request merged**
